/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package converter;

import java.awt.Color;

/**
 *
 * @author RAHUL
 */
public class Area extends javax.swing.JFrame {

    /**
     * Creates new form Area
     */
    public Area() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 102));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("AREA   CONVERTER");
        jLabel1.setToolTipText("");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Square Kilometre", "Square Metre", "Square Mile", "Square Yard", "Square Foot", "Square Inch", "Hectare", "Acre" }));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Square Kilometre", "Square Metre", "Square Mile", "Square Yard", "Square Foot", "Square Inch", "Hectare", "Acre" }));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setText("MENU");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setText("EXIT");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setText("TO");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("-A NOSCIP TECH PRODUCT");

        jLabel3.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("By Hritik jain");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(286, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(572, 572, 572))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(146, 146, 146)
                        .addComponent(jButton3)
                        .addGap(148, 148, 148)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(267, 267, 267))
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(152, 152, 152)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(101, 101, 101)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 246, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(111, 111, 111)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
 FrstFrame f= new FrstFrame();
 f.getContentPane().setBackground(Color.DARK_GRAY);
 f.setExtendedState(MAXIMIZED_BOTH);
f.setVisible(true);
this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
// TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
/*Square Kilometre
Square Metre
Square Mile
Square Yard
Square Foot
Square Inch
Hectare
Acre*/
if(jComboBox1.getSelectedItem()=="Square Kilometre"&&jComboBox2.getSelectedItem()=="Square Kilometre")
{
    String a=jTextField1.getText();
    float a1=Float.parseFloat(a);
float c1=a1;
jTextField2.setText(Float.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Square Kilometre"&&jComboBox2.getSelectedItem()=="Square Metre")
{
    String a=jTextField1.getText();
    float a1=Float.parseFloat(a);
float c1=a1*(1000000);
jTextField2.setText(Float.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Square Kilometre"&&jComboBox2.getSelectedItem()=="Square Mile")
{
    String a=jTextField1.getText();
    float a1=Float.parseFloat(a);
double c1=0.386102*a1;
jTextField2.setText(Double.toString(c1)); 
}
// TODO add your handling code here:1196000
else if(jComboBox1.getSelectedItem()=="Square Kilometre"&&jComboBox2.getSelectedItem()=="Square Yard")
{
    String a=jTextField1.getText();
    float a1=Float.parseFloat(a);
double c1=1196000*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Square Kilometre"&&jComboBox2.getSelectedItem()=="Square Foot")
{
    String a=jTextField1.getText();
    float a1=Float.parseFloat(a);
double c1=10760000*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Square Kilometre"&&jComboBox2.getSelectedItem()=="Square Inch")
{
    String a=jTextField1.getText();
    float a1=Float.parseFloat(a);
double c1=1550000000*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Square Kilometre"&&jComboBox2.getSelectedItem()=="Hectare")
{
    String a=jTextField1.getText();
    float a1=Float.parseFloat(a);
double c1=100*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Square Kilometre"&&jComboBox2.getSelectedItem()=="Acre")
{
    String a=jTextField1.getText();
    float a1=Float.parseFloat(a);
double c1=247.105*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Square Metre"&&jComboBox2.getSelectedItem()=="Square Kilometre")
{
    String a=jTextField1.getText();
    float a1=Float.parseFloat(a);
double c1=0.000001*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Square Metre"&&jComboBox2.getSelectedItem()=="Square Metre")
{
    String a=jTextField1.getText();
    float a1=Float.parseFloat(a);
double c1=a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Square Metre"&&jComboBox2.getSelectedItem()=="Square Mile")
{
    String a=jTextField1.getText();
    float a1=Float.parseFloat(a);
double c1=3.861e-7*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Square Metre"&&jComboBox2.getSelectedItem()=="Square Yard")
{
    String a=jTextField1.getText();
    float a1=Float.parseFloat(a);
double c1=1.19599*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Square Metre"&&jComboBox2.getSelectedItem()=="Square Foot")
{
    String a=jTextField1.getText();
    float a1=Float.parseFloat(a);
double c1=10.7639*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Square Metre"&&jComboBox2.getSelectedItem()=="Square Inch")
{
    String a=jTextField1.getText();
    float a1=Float.parseFloat(a);
double c1=1550*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Square Metre"&&jComboBox2.getSelectedItem()=="Hectare")
{
    String a=jTextField1.getText();
    float a1=Float.parseFloat(a);
double c1=0.00001*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Square Metre"&&jComboBox2.getSelectedItem()=="Acre")
{
    String a=jTextField1.getText();
    float a1=Float.parseFloat(a);
double c1=0.000247105*a1;
jTextField2.setText(Double.toString(c1)); 
}

else if(jComboBox1.getSelectedItem()=="Square Mile"&&jComboBox2.getSelectedItem()=="Square Kilometre")
{
    String a=jTextField1.getText();
    float a1=Float.parseFloat(a);
double c1=2.58999*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Square Mile"&&jComboBox2.getSelectedItem()=="Square Metre")
{
    String a=jTextField1.getText();
    float a1=Float.parseFloat(a);
double c1=2590000*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Square Mile"&&jComboBox2.getSelectedItem()=="Square Mile")
{
    String a=jTextField1.getText();
    float a1=Float.parseFloat(a);
double c1=a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Square Mile"&&jComboBox2.getSelectedItem()=="Square Yard")
{
    String a=jTextField1.getText();
    float a1=Float.parseFloat(a);
double c1=(3.098e+6)*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Square Mile"&&jComboBox2.getSelectedItem()=="Square Foot")
{
    String a=jTextField1.getText();
    float a1=Float.parseFloat(a);
double c1=(2.788e+7)*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Square Mile"&&jComboBox2.getSelectedItem()=="Square Inch")
{
    String a=jTextField1.getText();
    float a1=Float.parseFloat(a);
double c1=(4.014e+9)*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Square Mile"&&jComboBox2.getSelectedItem()=="Hectare")
{
    String a=jTextField1.getText();
    float a1=Float.parseFloat(a);
double c1=258.999*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Square Mile"&&jComboBox2.getSelectedItem()=="Acre")
{
    String a=jTextField1.getText();
    float a1=Float.parseFloat(a);
double c1=640*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Square Yard"&&jComboBox2.getSelectedItem()=="Square Kilometre")
{
    String a=jTextField1.getText();
    float a1=Float.parseFloat(a);
double c1=8.3613e-7*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Square Yard"&&jComboBox2.getSelectedItem()=="Square Metre")
{
    String a=jTextField1.getText();
    float a1=Float.parseFloat(a);
double c1=0.836127*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Square Yard"&&jComboBox2.getSelectedItem()=="Square Mile")
{
    String a=jTextField1.getText();
    float a1=Float.parseFloat(a);
double c1=3.2283e-7*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Square Yard"&&jComboBox2.getSelectedItem()=="Square Yard")
{
    String a=jTextField1.getText();
    float a1=Float.parseFloat(a);
double c1=a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Square Yard"&&jComboBox2.getSelectedItem()=="Square Foot")
{
    String a=jTextField1.getText();
    float a1=Float.parseFloat(a);
double c1=9*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Square Yard"&&jComboBox2.getSelectedItem()=="Square Inch")
{
    String a=jTextField1.getText();
    float a1=Float.parseFloat(a);
double c1=1296*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Square Yard"&&jComboBox2.getSelectedItem()=="Hectare")
{
    String a=jTextField1.getText();
    float a1=Float.parseFloat(a);
double c1=8.3613e-5*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Square Yard"&&jComboBox2.getSelectedItem()=="Acre")
{
    String a=jTextField1.getText();
    float a1=Float.parseFloat(a);
double c1=0.000206612*a1;
jTextField2.setText(Double.toString(c1)); 
}

else if(jComboBox1.getSelectedItem()=="Square Foot"&&jComboBox2.getSelectedItem()=="Square Kilometre")
{
    String a=jTextField1.getText();
    float a1=Float.parseFloat(a);
double c1=9.2903e-8*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Square Foot"&&jComboBox2.getSelectedItem()=="Square Metre")
{
    String a=jTextField1.getText();
    float a1=Float.parseFloat(a);
double c1=0.092903*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Square Foot"&&jComboBox2.getSelectedItem()=="Square Mile")
{
    String a=jTextField1.getText();
    float a1=Float.parseFloat(a);
double c1=3.587e-8*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Square Foot"&&jComboBox2.getSelectedItem()=="Square Yard")
{
    String a=jTextField1.getText();
    float a1=Float.parseFloat(a);
double c1=.111111*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Square Foot"&&jComboBox2.getSelectedItem()=="Square Foot")
{
    String a=jTextField1.getText();
    float a1=Float.parseFloat(a);
double c1=a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Square Foot"&&jComboBox2.getSelectedItem()=="Square Inch")
{
    String a=jTextField1.getText();
    float a1=Float.parseFloat(a);
double c1=144*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Square Foot"&&jComboBox2.getSelectedItem()=="Hectare")
{
    String a=jTextField1.getText();
    float a1=Float.parseFloat(a);
double c1=9.2903e-6*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Square Foot"&&jComboBox2.getSelectedItem()=="Acre")
{
    String a=jTextField1.getText();
    float a1=Float.parseFloat(a);
double c1=2.2957e-5*a1;
jTextField2.setText(Double.toString(c1)); 
}

else if(jComboBox1.getSelectedItem()=="Square Inch"&&jComboBox2.getSelectedItem()=="Square Kilometre")
{
    String a=jTextField1.getText();
    float a1=Float.parseFloat(a);
double c1=6.4516e-10*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Square Inch"&&jComboBox2.getSelectedItem()=="Square Metre")
{
    String a=jTextField1.getText();
    float a1=Float.parseFloat(a);
double c1=0.00064516*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Square Inch"&&jComboBox2.getSelectedItem()=="Square Mile")
{
    String a=jTextField1.getText();
    float a1=Float.parseFloat(a);
double c1=2.491e-10*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Square Inch"&&jComboBox2.getSelectedItem()=="Square Yard")
{
    String a=jTextField1.getText();
    float a1=Float.parseFloat(a);
double c1=0.000771605*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Square Inch"&&jComboBox2.getSelectedItem()=="Square Foot")
{
    String a=jTextField1.getText();
    float a1=Float.parseFloat(a);
double c1=0.00694444*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Square Inch"&&jComboBox2.getSelectedItem()=="Square Inch")
{
    String a=jTextField1.getText();
    float a1=Float.parseFloat(a);
double c1=a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Square Inch"&&jComboBox2.getSelectedItem()=="Hectare")
{
    String a=jTextField1.getText();
    float a1=Float.parseFloat(a);
double c1=6.4516e-8*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Square Inch"&&jComboBox2.getSelectedItem()=="Acre")
{
    String a=jTextField1.getText();
    float a1=Float.parseFloat(a);
double c1=1.5942e-7*a1;
jTextField2.setText(Double.toString(c1)); 
}

else if(jComboBox1.getSelectedItem()=="Hectare"&&jComboBox2.getSelectedItem()=="Square Kilometre")
{
    String a=jTextField1.getText();
    float a1=Float.parseFloat(a);
double c1=.01*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Hectare"&&jComboBox2.getSelectedItem()=="Square Metre")
{
    String a=jTextField1.getText();
    float a1=Float.parseFloat(a);
double c1=10000*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Hectare"&&jComboBox2.getSelectedItem()=="Square Mile")
{
    String a=jTextField1.getText();
    float a1=Float.parseFloat(a);
double c1=0.00386102*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Hectare"&&jComboBox2.getSelectedItem()=="Square Yard")
{
    String a=jTextField1.getText();
    float a1=Float.parseFloat(a);
double c1=11959.9*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Hectare"&&jComboBox2.getSelectedItem()=="Square Foot")
{
    String a=jTextField1.getText();
    float a1=Float.parseFloat(a);
double c1=107639*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Hectare"&&jComboBox2.getSelectedItem()=="Square Inch")
{
    String a=jTextField1.getText();
    float a1=Float.parseFloat(a);
double c1=15500000*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Hectare"&&jComboBox2.getSelectedItem()=="Hectare")
{
    String a=jTextField1.getText();
    float a1=Float.parseFloat(a);
double c1=a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Hectare"&&jComboBox2.getSelectedItem()=="Acre")
{
    String a=jTextField1.getText();
    float a1=Float.parseFloat(a);
double c1=2.47105*a1;
jTextField2.setText(Double.toString(c1)); 
}

else if(jComboBox1.getSelectedItem()=="Acre"&&jComboBox2.getSelectedItem()=="Square Kilometre")
{
    String a=jTextField1.getText();
    float a1=Float.parseFloat(a);
double c1=0.00404686*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Acre"&&jComboBox2.getSelectedItem()=="Square Metre")
{
    String a=jTextField1.getText();
    float a1=Float.parseFloat(a);
double c1=4046.86*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Acre"&&jComboBox2.getSelectedItem()=="Square Mile")
{
    String a=jTextField1.getText();
    float a1=Float.parseFloat(a);
double c1=0.0015625*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Acre"&&jComboBox2.getSelectedItem()=="Square Yard")
{
    String a=jTextField1.getText();
    float a1=Float.parseFloat(a);
double c1=4840*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Acre"&&jComboBox2.getSelectedItem()=="Square Foot")
{
    String a=jTextField1.getText();
    float a1=Float.parseFloat(a);
double c1=43560*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Acre"&&jComboBox2.getSelectedItem()=="Square Inch")
{
    String a=jTextField1.getText();
    float a1=Float.parseFloat(a);
double c1=6.273e+6*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Acre"&&jComboBox2.getSelectedItem()=="Hectare")
{
    String a=jTextField1.getText();
    float a1=Float.parseFloat(a);
double c1=0.404686*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Acre"&&jComboBox2.getSelectedItem()=="Acre")
{
    String a=jTextField1.getText();
    float a1=Float.parseFloat(a);
double c1=a1;
jTextField2.setText(Double.toString(c1)); 
}

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
System.exit(0);         // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Area.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Area.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Area.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Area.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Area().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
