/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package converter;

import java.awt.Color;
import static java.awt.Frame.MAXIMIZED_BOTH;

/**
 *
 * @author RAHUL
 */
public class Data extends javax.swing.JFrame {

    /**
     * Creates new form Data
     */
    public Data() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setText("EXIT");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 153));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("DATA TRANSFER RATE  CONVERTER");
        jLabel1.setToolTipText("");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bit Per Second", "Kilobit Per Second", "Kilobyte Per Second", "kibibit Per Second", "Megabit Per Second", "Megabyte Per Second", "Mebibit Per Second", "Gigabit Per Second", "Gigabyte Per Second", "Gibibit Per Second", "Terabit Per Second", "Terabyte Per Second", "Tebibit Per Second" }));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bit Per Second", "Kilobit Per Second", "Kilobyte Per Second", "kibibit Per Second", "Megabit Per Second", "Megabyte Per Second", "Mebibit Per Second", "Gigabit Per Second", "Gigabyte Per Second", "Gibibit Per Second", "Terabit Per Second", "Terabyte Per Second", "Tebibit Per Second" }));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setText("MENU");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setText("TO");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("-A NOSCIP TECH PRODUCT");

        jLabel3.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("By Hritik jain");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(231, 231, 231)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(145, 145, 145)
                        .addComponent(jButton3)
                        .addGap(142, 142, 142)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(470, 470, 470)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(219, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(90, 90, 90)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(186, 186, 186)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 173, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(137, 137, 137)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
 FrstFrame f= new FrstFrame();
 f.getContentPane().setBackground(Color.DARK_GRAY);
 f.setExtendedState(MAXIMIZED_BOTH);
f.setVisible(true);
this.dispose();     // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

if(jComboBox1.getSelectedItem()=="Bit Per Second"&&jComboBox2.getSelectedItem()=="Bit Per Second")
{
    String a=jTextField1.getText();
    float a1=Float.parseFloat(a);
float c1=a1;
jTextField2.setText(Float.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Bit Per Second"&&jComboBox2.getSelectedItem()=="Kilobit Per Second")
{
    String a=jTextField1.getText();
    float a1=Float.parseFloat(a);
double c1=0.001*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Bit Per Second"&&jComboBox2.getSelectedItem()=="Kilobyte Per Second")
{
    String a=jTextField1.getText();
    float a1=Float.parseFloat(a);
double c1=0.000125*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Bit Per Second"&&jComboBox2.getSelectedItem()=="Kibibit Per Second")
{
    String a=jTextField1.getText();
    float a1=Float.parseFloat(a);
double c1=0.000976563*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Bit Per Second"&&jComboBox2.getSelectedItem()=="Megabit Per Second")
{
    String a=jTextField1.getText();
    float a1=Float.parseFloat(a);
double c1=0.000001*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Bit Per Second"&&jComboBox2.getSelectedItem()=="Megabyte Per Second")
{
    String a=jTextField1.getText();
    float a1=Float.parseFloat(a);
double c1=0.000000125*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Bit Per Second"&&jComboBox2.getSelectedItem()=="Mebibit Per Second")
{
    String a=jTextField1.getText();
    float a1=Float.parseFloat(a);
double c1=9.5367e-7*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Bit Per Second"&&jComboBox2.getSelectedItem()=="Gigabit Per Second")
{
    String a=jTextField1.getText();
    float a1=Float.parseFloat(a);
double c1=0.000000001*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Bit Per Second"&&jComboBox2.getSelectedItem()=="Gigabyte Per Second")
{
    String a=jTextField1.getText();
    float a1=Float.parseFloat(a);
double c1=1.25e-10*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Bit Per Second"&&jComboBox2.getSelectedItem()=="Gibibit Per Second")
{
    String a=jTextField1.getText();
    float a1=Float.parseFloat(a);
double c1=9.3132e-10*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Bit Per Second"&&jComboBox2.getSelectedItem()=="Terabit Per Second")
{
    String a=jTextField1.getText();
    float a1=Float.parseFloat(a);
double c1=1e-12*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Bit Per Second"&&jComboBox2.getSelectedItem()=="Terabyte Per Second")
{
    String a=jTextField1.getText();
    float a1=Float.parseFloat(a);
double c1=1.25e-13*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Bit Per Second"&&jComboBox2.getSelectedItem()=="Tebibit Per Second")
{
    String a=jTextField1.getText();
    float a1=Float.parseFloat(a);
double c1=9.0949e-13*a1;
jTextField2.setText(Double.toString(c1)); 
}

else if(jComboBox1.getSelectedItem()=="Kilobit Per Second"&&jComboBox2.getSelectedItem()=="Bit Per Second")
{
    String a=jTextField1.getText();
    float a1=Float.parseFloat(a);
float c1=1000*a1;
jTextField2.setText(Float.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Kilobit Per Second"&&jComboBox2.getSelectedItem()=="Kilobit Per Second")
{
    String a=jTextField1.getText();
    float a1=Float.parseFloat(a);
double c1=a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Kilobit Per Second"&&jComboBox2.getSelectedItem()=="Kilobyte Per Second")
{
    String a=jTextField1.getText();
    float a1=Float.parseFloat(a);
double c1=0.125*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Kilobit Per Second"&&jComboBox2.getSelectedItem()=="Kibibit Per Second")
{
    String a=jTextField1.getText();
    float a1=Float.parseFloat(a);
double c1=0.976563*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Kilobit Per Second"&&jComboBox2.getSelectedItem()=="Megabit Per Second")
{
    String a=jTextField1.getText();
    float a1=Float.parseFloat(a);
double c1=0.001*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Kilobit Per Second"&&jComboBox2.getSelectedItem()=="Megabyte Per Second")
{
    String a=jTextField1.getText();
    float a1=Float.parseFloat(a);
double c1=0.000125*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Kilobit Per Second"&&jComboBox2.getSelectedItem()=="Mebibit Per Second")
{
    String a=jTextField1.getText();
    float a1=Float.parseFloat(a);
double c1=0.000953674*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Kilobit Per Second"&&jComboBox2.getSelectedItem()=="Gigabit Per Second")
{
    String a=jTextField1.getText();
    float a1=Float.parseFloat(a);
double c1=1e-6*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Kilobit Per Second"&&jComboBox2.getSelectedItem()=="Gigabyte Per Second")
{
    String a=jTextField1.getText();
    float a1=Float.parseFloat(a);
double c1=1.25e-7*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Kilobit Per Second"&&jComboBox2.getSelectedItem()=="Gibibit Per Second")
{
    String a=jTextField1.getText();
    float a1=Float.parseFloat(a);
double c1=9.3132e-7*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Kilobit Per Second"&&jComboBox2.getSelectedItem()=="Terabit Per Second")
{
    String a=jTextField1.getText();
    float a1=Float.parseFloat(a);
double c1=1e-9*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Kilobit Per Second"&&jComboBox2.getSelectedItem()=="Terabyte Per Second")
{
    String a=jTextField1.getText();
    float a1=Float.parseFloat(a);
double c1=1.25e-10*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Kilobit Per Second"&&jComboBox2.getSelectedItem()=="Tebibit Per Second")
{
    String a=jTextField1.getText();
    float a1=Float.parseFloat(a);
double c1=9.0949e-10*a1;
jTextField2.setText(Double.toString(c1)); 
}

else if(jComboBox1.getSelectedItem()=="Kilobyte Per Second"&&jComboBox2.getSelectedItem()=="Bit Per Second")
{
    String a=jTextField1.getText();
    float a1=Float.parseFloat(a);
float c1=8000*a1;
jTextField2.setText(Float.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Kilobyte Per Second"&&jComboBox2.getSelectedItem()=="Kilobit Per Second")
{
    String a=jTextField1.getText();
    float a1=Float.parseFloat(a);
double c1=8*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Kilobyte Per Second"&&jComboBox2.getSelectedItem()=="Kilobyte Per Second")
{
    String a=jTextField1.getText();
    float a1=Float.parseFloat(a);
double c1=a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Kilobyte Per Second"&&jComboBox2.getSelectedItem()=="Kibibit Per Second")
{
    String a=jTextField1.getText();
    float a1=Float.parseFloat(a);
double c1=7.8125*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Kilobyte Per Second"&&jComboBox2.getSelectedItem()=="Megabit Per Second")
{
    String a=jTextField1.getText();
    float a1=Float.parseFloat(a);
double c1=0.008*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Kilobyte Per Second"&&jComboBox2.getSelectedItem()=="Megabyte Per Second")
{
    String a=jTextField1.getText();
    float a1=Float.parseFloat(a);
double c1=0.001*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Kilobyte Per Second"&&jComboBox2.getSelectedItem()=="Mebibit Per Second")
{
    String a=jTextField1.getText();
    float a1=Float.parseFloat(a);
double c1=0.00762939*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Kilobyte Per Second"&&jComboBox2.getSelectedItem()=="Gigabit Per Second")
{
    String a=jTextField1.getText();
    float a1=Float.parseFloat(a);
double c1=8e-6*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Kilobyte Per Second"&&jComboBox2.getSelectedItem()=="Gigabyte Per Second")
{
    String a=jTextField1.getText();
    float a1=Float.parseFloat(a);
double c1=1e-6*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Kilobyte Per Second"&&jComboBox2.getSelectedItem()=="Gibibit Per Second")
{
    String a=jTextField1.getText();
    float a1=Float.parseFloat(a);
double c1=7.4506e-6*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Kilobyte Per Second"&&jComboBox2.getSelectedItem()=="Terabit Per Second")
{
    String a=jTextField1.getText();
    float a1=Float.parseFloat(a);
double c1=8e-9*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Kilobyte Per Second"&&jComboBox2.getSelectedItem()=="Terabyte Per Second")
{
    String a=jTextField1.getText();
    float a1=Float.parseFloat(a);
double c1=1e-9*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Kilobyte Per Second"&&jComboBox2.getSelectedItem()=="Tebibit Per Second")
{
    String a=jTextField1.getText();
    float a1=Float.parseFloat(a);
double c1=7.276e-9*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Kibibit Per Second"&&jComboBox2.getSelectedItem()=="Bit Per Second")
{
    String a=jTextField1.getText();
    float a1=Float.parseFloat(a);
float c1=1024*a1;
jTextField2.setText(Float.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Kibibit Per Second"&&jComboBox2.getSelectedItem()=="Kilobit Per Second")
{
    String a=jTextField1.getText();
    float a1=Float.parseFloat(a);
double c1=1.024*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Kibibit Per Second"&&jComboBox2.getSelectedItem()=="Kilobyte Per Second")
{
    String a=jTextField1.getText();
    float a1=Float.parseFloat(a);
double c1=0.128*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Kibibit Per Second"&&jComboBox2.getSelectedItem()=="Kibibit Per Second")
{
    String a=jTextField1.getText();
    float a1=Float.parseFloat(a);
double c1=a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Kibibit Per Second"&&jComboBox2.getSelectedItem()=="Megabit Per Second")
{
    String a=jTextField1.getText();
    float a1=Float.parseFloat(a);
double c1=0.001024*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Kibibit Per Second"&&jComboBox2.getSelectedItem()=="Megabyte Per Second")
{
    String a=jTextField1.getText();
    float a1=Float.parseFloat(a);
double c1=0.000128*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Kibibit Per Second"&&jComboBox2.getSelectedItem()=="Mebibit Per Second")
{
    String a=jTextField1.getText();
    float a1=Float.parseFloat(a);
double c1=0.000976563*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Kibibit Per Second"&&jComboBox2.getSelectedItem()=="Gigabit Per Second")
{
    String a=jTextField1.getText();
    float a1=Float.parseFloat(a);
double c1=1.024e-6*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Kibibit Per Second"&&jComboBox2.getSelectedItem()=="Gigabyte Per Second")
{
    String a=jTextField1.getText();
    float a1=Float.parseFloat(a);
double c1=1.28e-7*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Kibibit Per Second"&&jComboBox2.getSelectedItem()=="Gibibit Per Second")
{
    String a=jTextField1.getText();
    float a1=Float.parseFloat(a);
double c1=9.5367e-7*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Kibibit Per Second"&&jComboBox2.getSelectedItem()=="Terabit Per Second")
{
    String a=jTextField1.getText();
    float a1=Float.parseFloat(a);
double c1=1.024e-9*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Kibibit Per Second"&&jComboBox2.getSelectedItem()=="Terabyte Per Second")
{
    String a=jTextField1.getText();
    float a1=Float.parseFloat(a);
double c1=1.28e-10*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Kibibit Per Second"&&jComboBox2.getSelectedItem()=="Tebibit Per Second")
{
    String a=jTextField1.getText();
    float a1=Float.parseFloat(a);
double c1=9.3132e-10*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Megabit Per Second"&&jComboBox2.getSelectedItem()=="Bit Per Second")
{
    String a=jTextField1.getText();
    float a1=Float.parseFloat(a);
double c1=1e+6*a1;
jTextField2.setText(Double.toString(c1));  
}
else if(jComboBox1.getSelectedItem()=="Megabit Per Second"&&jComboBox2.getSelectedItem()=="Kilobit Per Second")
{
    String a=jTextField1.getText();
    float a1=Float.parseFloat(a);
double c1=1000*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Megabit Per Second"&&jComboBox2.getSelectedItem()=="Kilobyte Per Second")
{
    String a=jTextField1.getText();
    float a1=Float.parseFloat(a);
double c1=125*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Megabit Per Second"&&jComboBox2.getSelectedItem()=="Kibibit Per Second")
{
    String a=jTextField1.getText();
    float a1=Float.parseFloat(a);
double c1=976.563*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Megabit Per Second"&&jComboBox2.getSelectedItem()=="Megabit Per Second")
{
    String a=jTextField1.getText();
    float a1=Float.parseFloat(a);
double c1=a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Megabit Per Second"&&jComboBox2.getSelectedItem()=="Megabyte Per Second")
{
    String a=jTextField1.getText();
    float a1=Float.parseFloat(a);
double c1=0.125*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Megabit Per Second"&&jComboBox2.getSelectedItem()=="Mebibit Per Second")
{
    String a=jTextField1.getText();
    float a1=Float.parseFloat(a);
double c1=0.953674*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Megabit Per Second"&&jComboBox2.getSelectedItem()=="Gigabit Per Second")
{
    String a=jTextField1.getText();
    float a1=Float.parseFloat(a);
double c1=0.001*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Megabit Per Second"&&jComboBox2.getSelectedItem()=="Gigabyte Per Second")
{
    String a=jTextField1.getText();
    float a1=Float.parseFloat(a);
double c1=0.000125*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Megabit Per Second"&&jComboBox2.getSelectedItem()=="Gibibit Per Second")
{
    String a=jTextField1.getText();
    float a1=Float.parseFloat(a);
double c1=0.000931323*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Megabit Per Second"&&jComboBox2.getSelectedItem()=="Terabit Per Second")
{
    String a=jTextField1.getText();
    float a1=Float.parseFloat(a);
double c1=1e-6*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Megabit Per Second"&&jComboBox2.getSelectedItem()=="Terabyte Per Second")
{
    String a=jTextField1.getText();
    float a1=Float.parseFloat(a);
double c1=1.25e-7*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Megabit Per Second"&&jComboBox2.getSelectedItem()=="Tebibit Per Second")
{
    String a=jTextField1.getText();
    float a1=Float.parseFloat(a);
double c1=a1/( 1.1e+6);
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Megabyte Per Second"&&jComboBox2.getSelectedItem()=="Bit Per Second")
{
    String a=jTextField1.getText();
    float a1=Float.parseFloat(a);
double c1=8e+6*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Megabyte Per Second"&&jComboBox2.getSelectedItem()=="Kilobit Per Second")
{
    String a=jTextField1.getText();
    float a1=Float.parseFloat(a);
double c1=8000*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Megabyte Per Second"&&jComboBox2.getSelectedItem()=="Kilobyte Per Second")
{
    String a=jTextField1.getText();
    float a1=Float.parseFloat(a);
double c1=1000*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Megabyte Per Second"&&jComboBox2.getSelectedItem()=="Kibibit Per Second")
{
    String a=jTextField1.getText();
    float a1=Float.parseFloat(a);
double c1=7812.5*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Megabyte Per Second"&&jComboBox2.getSelectedItem()=="Megabit Per Second")
{
    String a=jTextField1.getText();
    float a1=Float.parseFloat(a);
double c1=8*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Megabyte Per Second"&&jComboBox2.getSelectedItem()=="Megabyte Per Second")
{
    String a=jTextField1.getText();
    float a1=Float.parseFloat(a);
double c1=a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Megabyte Per Second"&&jComboBox2.getSelectedItem()=="Mebibit Per Second")
{
    String a=jTextField1.getText();
    float a1=Float.parseFloat(a);
double c1=7.62939*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Megabyte Per Second"&&jComboBox2.getSelectedItem()=="Gigabit Per Second")
{
    String a=jTextField1.getText();
    float a1=Float.parseFloat(a);
double c1=0.008*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Megabyte Per Second"&&jComboBox2.getSelectedItem()=="Gigabyte Per Second")
{
    String a=jTextField1.getText();
    float a1=Float.parseFloat(a);
double c1=0.001*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Megabyte Per Second"&&jComboBox2.getSelectedItem()=="Gibibit Per Second")
{
    String a=jTextField1.getText();
    float a1=Float.parseFloat(a);
double c1=0.00745058*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Megabyte Per Second"&&jComboBox2.getSelectedItem()=="Terabit Per Second")
{
    String a=jTextField1.getText();
    float a1=Float.parseFloat(a);
double c1=8e-6*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Megabyte Per Second"&&jComboBox2.getSelectedItem()=="Terabyte Per Second")
{
    String a=jTextField1.getText();
    float a1=Float.parseFloat(a);
double c1=1e-6*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Megabyte Per Second"&&jComboBox2.getSelectedItem()=="Tebibit Per Second")
{
    String a=jTextField1.getText();
    float a1=Float.parseFloat(a);
double c1=7.276e-6*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Mebibit Per Second"&&jComboBox2.getSelectedItem()=="Bit Per Second")
{
    String a=jTextField1.getText();
    float a1=Float.parseFloat(a);
double c1=1.049e+6*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Mebibit Per Second"&&jComboBox2.getSelectedItem()=="Kilobit Per Second")
{
    String a=jTextField1.getText();
    float a1=Float.parseFloat(a);
double c1=1048.58*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Mebibit Per Second"&&jComboBox2.getSelectedItem()=="Kilobyte Per Second")
{
    String a=jTextField1.getText();
    float a1=Float.parseFloat(a);
double c1=131.072*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Mebibit Per Second"&&jComboBox2.getSelectedItem()=="Kibibit Per Second")
{
    String a=jTextField1.getText();
    float a1=Float.parseFloat(a);
double c1=1024*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Mebibit Per Second"&&jComboBox2.getSelectedItem()=="Megabit Per Second")
{
    String a=jTextField1.getText();
    float a1=Float.parseFloat(a);
double c1=1.04858*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Mebibit Per Second"&&jComboBox2.getSelectedItem()=="Megabyte Per Second")
{
    String a=jTextField1.getText();
    float a1=Float.parseFloat(a);
double c1=0.131072*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Mebibit Per Second"&&jComboBox2.getSelectedItem()=="Mebibit Per Second")
{
    String a=jTextField1.getText();
    float a1=Float.parseFloat(a);
double c1=a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Mebibit Per Second"&&jComboBox2.getSelectedItem()=="Gigabit Per Second")
{
    String a=jTextField1.getText();
    float a1=Float.parseFloat(a);
double c1=0.00104858*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Mebibit Per Second"&&jComboBox2.getSelectedItem()=="Gigabyte Per Second")
{
    String a=jTextField1.getText();
    float a1=Float.parseFloat(a);
double c1=0.000131072*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Mebibit Per Second"&&jComboBox2.getSelectedItem()=="Gibibit Per Second")
{
    String a=jTextField1.getText();
    float a1=Float.parseFloat(a);
double c1=0.000976563*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Mebibit Per Second"&&jComboBox2.getSelectedItem()=="Terabit Per Second")
{
    String a=jTextField1.getText();
    float a1=Float.parseFloat(a);
double c1=1.0486e-6*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Mebibit Per Second"&&jComboBox2.getSelectedItem()=="Terabyte Per Second")
{
    String a=jTextField1.getText();
    float a1=Float.parseFloat(a);
double c1=1.3107e-7*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Mebibit Per Second"&&jComboBox2.getSelectedItem()=="Tebibit Per Second")
{
    String a=jTextField1.getText();
    float a1=Float.parseFloat(a);
double c1=9.5367e-7*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Gigabit Per Second"&&jComboBox2.getSelectedItem()=="Bit Per Second")
{
    String a=jTextField1.getText();
    float a1=Float.parseFloat(a);
double c1=1e+9*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Gigabit Per Second"&&jComboBox2.getSelectedItem()=="Kilobit Per Second")
{
    String a=jTextField1.getText();
    float a1=Float.parseFloat(a);
double c1=1e+6*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Gigabit Per Second"&&jComboBox2.getSelectedItem()=="Kilobyte Per Second")
{
    String a=jTextField1.getText();
    float a1=Float.parseFloat(a);
double c1=125000*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Gigabit Per Second"&&jComboBox2.getSelectedItem()=="Kibibit Per Second")
{
    String a=jTextField1.getText();
    float a1=Float.parseFloat(a);
double c1=976563*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Gigabit Per Second"&&jComboBox2.getSelectedItem()=="Megabit Per Second")
{
    String a=jTextField1.getText();
    float a1=Float.parseFloat(a);
double c1=1000*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Gigabit Per Second"&&jComboBox2.getSelectedItem()=="Megabyte Per Second")
{
    String a=jTextField1.getText();
    float a1=Float.parseFloat(a);
double c1=125*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Gigabit Per Second"&&jComboBox2.getSelectedItem()=="Mebibit Per Second")
{
    String a=jTextField1.getText();
    float a1=Float.parseFloat(a);
double c1=953.674*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Gigabit Per Second"&&jComboBox2.getSelectedItem()=="Gigabit Per Second")
{
    String a=jTextField1.getText();
    float a1=Float.parseFloat(a);
double c1=a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Gigabit Per Second"&&jComboBox2.getSelectedItem()=="Gigabyte Per Second")
{
    String a=jTextField1.getText();
    float a1=Float.parseFloat(a);
double c1=0.125*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Gigabit Per Second"&&jComboBox2.getSelectedItem()=="Gibibit Per Second")
{
    String a=jTextField1.getText();
    float a1=Float.parseFloat(a);
double c1=0.931323*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Gigabit Per Second"&&jComboBox2.getSelectedItem()=="Terabit Per Second")
{
    String a=jTextField1.getText();
    float a1=Float.parseFloat(a);
double c1=0.001*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Gigabit Per Second"&&jComboBox2.getSelectedItem()=="Terabyte Per Second")
{
    String a=jTextField1.getText();
    float a1=Float.parseFloat(a);
double c1=0.000125*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Gigabit Per Second"&&jComboBox2.getSelectedItem()=="Tebibit Per Second")
{
    String a=jTextField1.getText();
    float a1=Float.parseFloat(a);
double c1=0.000909495*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Gigabyte Per Second"&&jComboBox2.getSelectedItem()=="Bit Per Second")
{
    String a=jTextField1.getText();
    float a1=Float.parseFloat(a);
double c1=8e+9*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Gigabyte Per Second"&&jComboBox2.getSelectedItem()=="Kilobit Per Second")
{
    String a=jTextField1.getText();
    float a1=Float.parseFloat(a);
double c1=8e+6*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Gigabyte Per Second"&&jComboBox2.getSelectedItem()=="Kilobyte Per Second")
{
    String a=jTextField1.getText();
    float a1=Float.parseFloat(a);
double c1=1e+6*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Gigabyte Per Second"&&jComboBox2.getSelectedItem()=="Kibibit Per Second")
{
    String a=jTextField1.getText();
    float a1=Float.parseFloat(a);
double c1=7.813e+6*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Gigabyte Per Second"&&jComboBox2.getSelectedItem()=="Megabit Per Second")
{
    String a=jTextField1.getText();
    float a1=Float.parseFloat(a);
double c1=8000*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Gigabyte Per Second"&&jComboBox2.getSelectedItem()=="Megabyte Per Second")
{
    String a=jTextField1.getText();
    float a1=Float.parseFloat(a);
double c1=1000*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Gigabyte Per Second"&&jComboBox2.getSelectedItem()=="Mebibit Per Second")
{
    String a=jTextField1.getText();
    float a1=Float.parseFloat(a);
double c1=7629.39*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Gigabyte Per Second"&&jComboBox2.getSelectedItem()=="Gigabit Per Second")
{
    String a=jTextField1.getText();
    float a1=Float.parseFloat(a);
double c1=8*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Gigabyte Per Second"&&jComboBox2.getSelectedItem()=="Gigabyte Per Second")
{
    String a=jTextField1.getText();
    float a1=Float.parseFloat(a);
double c1=a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Gigabyte Per Second"&&jComboBox2.getSelectedItem()=="Gibibit Per Second")
{
    String a=jTextField1.getText();
    float a1=Float.parseFloat(a);
double c1=7.45058*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Gigabyte Per Second"&&jComboBox2.getSelectedItem()=="Terabit Per Second")
{
    String a=jTextField1.getText();
    float a1=Float.parseFloat(a);
double c1=0.008*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Gigabyte Per Second"&&jComboBox2.getSelectedItem()=="Terabyte Per Second")
{
    String a=jTextField1.getText();
    float a1=Float.parseFloat(a);
double c1=0.001*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Gigabyte Per Second"&&jComboBox2.getSelectedItem()=="Tebibit Per Second")
{
    String a=jTextField1.getText();
    float a1=Float.parseFloat(a);
double c1=0.00727596*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Gibibit Per Second"&&jComboBox2.getSelectedItem()=="Bit Per Second")
{
    String a=jTextField1.getText();
    float a1=Float.parseFloat(a);
double c1=1.074e+9*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Gibibit Per Second"&&jComboBox2.getSelectedItem()=="Kilobit Per Second")
{
    String a=jTextField1.getText();
    float a1=Float.parseFloat(a);
double c1=1.074e+6*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Gibibit Per Second"&&jComboBox2.getSelectedItem()=="Kilobyte Per Second")
{
    String a=jTextField1.getText();
    float a1=Float.parseFloat(a);
double c1=134218*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Gibibit Per Second"&&jComboBox2.getSelectedItem()=="Kibibit Per Second")
{
    String a=jTextField1.getText();
    float a1=Float.parseFloat(a);
double c1=1.049e+6*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Gibibit Per Second"&&jComboBox2.getSelectedItem()=="Megabit Per Second")
{
    String a=jTextField1.getText();
    float a1=Float.parseFloat(a);
double c1=1073.74*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Gibibit Per Second"&&jComboBox2.getSelectedItem()=="Megabyte Per Second")
{
    String a=jTextField1.getText();
    float a1=Float.parseFloat(a);
double c1=134.218*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Gibibit Per Second"&&jComboBox2.getSelectedItem()=="Mebibit Per Second")
{
    String a=jTextField1.getText();
    float a1=Float.parseFloat(a);
double c1=1024*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Gibibit Per Second"&&jComboBox2.getSelectedItem()=="Gigabit Per Second")
{
    String a=jTextField1.getText();
    float a1=Float.parseFloat(a);
double c1=1.07374*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Gibibit Per Second"&&jComboBox2.getSelectedItem()=="Gigabyte Per Second")
{
    String a=jTextField1.getText();
    float a1=Float.parseFloat(a);
double c1=0.134218*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Gibibit Per Second"&&jComboBox2.getSelectedItem()=="Gibibit Per Second")
{
    String a=jTextField1.getText();
    float a1=Float.parseFloat(a);
double c1=a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Gibibit Per Second"&&jComboBox2.getSelectedItem()=="Terabit Per Second")
{
    String a=jTextField1.getText();
    float a1=Float.parseFloat(a);
double c1=0.00107374*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Gibibit Per Second"&&jComboBox2.getSelectedItem()=="Terabyte Per Second")
{
    String a=jTextField1.getText();
    float a1=Float.parseFloat(a);
double c1=0.000134218*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Gibibit Per Second"&&jComboBox2.getSelectedItem()=="Tebibit Per Second")
{
    String a=jTextField1.getText();
    float a1=Float.parseFloat(a);
double c1=0.000976563*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Terabit Per Second"&&jComboBox2.getSelectedItem()=="Bit Per Second")
{
    String a=jTextField1.getText();
    float a1=Float.parseFloat(a);
double c1=1e+12*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Terabit Per Second"&&jComboBox2.getSelectedItem()=="Kilobit Per Second")
{
    String a=jTextField1.getText();
    float a1=Float.parseFloat(a);
double c1=1e+9*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Terabit Per Second"&&jComboBox2.getSelectedItem()=="Kilobyte Per Second")
{
    String a=jTextField1.getText();
    float a1=Float.parseFloat(a);
double c1=1.25e+8*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Terabit Per Second"&&jComboBox2.getSelectedItem()=="Kibibit Per Second")
{
    String a=jTextField1.getText();
    float a1=Float.parseFloat(a);
double c1=9.766e+8*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Terabit Per Second"&&jComboBox2.getSelectedItem()=="Megabit Per Second")
{
    String a=jTextField1.getText();
    float a1=Float.parseFloat(a);
double c1=1e+6*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Terabit Per Second"&&jComboBox2.getSelectedItem()=="Megabyte Per Second")
{
    String a=jTextField1.getText();
    float a1=Float.parseFloat(a);
double c1=125000*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Terabit Per Second"&&jComboBox2.getSelectedItem()=="Mebibit Per Second")
{
    String a=jTextField1.getText();
    float a1=Float.parseFloat(a);
double c1=953674*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Terabit Per Second"&&jComboBox2.getSelectedItem()=="Gigabit Per Second")
{
    String a=jTextField1.getText();
    float a1=Float.parseFloat(a);
double c1=1000*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Terabit Per Second"&&jComboBox2.getSelectedItem()=="Gigabyte Per Second")
{
    String a=jTextField1.getText();
    float a1=Float.parseFloat(a);
double c1=125*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Terabit Per Second"&&jComboBox2.getSelectedItem()=="Gibibit Per Second")
{
    String a=jTextField1.getText();
    float a1=Float.parseFloat(a);
double c1=931.323*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Terabit Per Second"&&jComboBox2.getSelectedItem()=="Terabit Per Second")
{
    String a=jTextField1.getText();
    float a1=Float.parseFloat(a);
double c1=a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Terabit Per Second"&&jComboBox2.getSelectedItem()=="Terabyte Per Second")
{
    String a=jTextField1.getText();
    float a1=Float.parseFloat(a);
double c1=0.125*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Terabit Per Second"&&jComboBox2.getSelectedItem()=="Tebibit Per Second")
{
    String a=jTextField1.getText();
    float a1=Float.parseFloat(a);
double c1=0.909495*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Terabyte Per Second"&&jComboBox2.getSelectedItem()=="Bit Per Second")
{
    String a=jTextField1.getText();
    float a1=Float.parseFloat(a);
double c1=8e+12*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Terabyte Per Second"&&jComboBox2.getSelectedItem()=="Kilobit Per Second")
{
    String a=jTextField1.getText();
    float a1=Float.parseFloat(a);
double c1=8e+9*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Terabyte Per Second"&&jComboBox2.getSelectedItem()=="Kilobyte Per Second")
{
    String a=jTextField1.getText();
    float a1=Float.parseFloat(a);
double c1=1e+9*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Terabyte Per Second"&&jComboBox2.getSelectedItem()=="Kibibit Per Second")
{
    String a=jTextField1.getText();
    float a1=Float.parseFloat(a);
double c1=7.813e+9*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Terabyte Per Second"&&jComboBox2.getSelectedItem()=="Megabit Per Second")
{
    String a=jTextField1.getText();
    float a1=Float.parseFloat(a);
double c1=8e+6*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Terabyte Per Second"&&jComboBox2.getSelectedItem()=="Megabyte Per Second")
{
    String a=jTextField1.getText();
    float a1=Float.parseFloat(a);
double c1=1e+6*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Terabyte Per Second"&&jComboBox2.getSelectedItem()=="Mebibit Per Second")
{
    String a=jTextField1.getText();
    float a1=Float.parseFloat(a);
double c1=7.629e+6*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Terabyte Per Second"&&jComboBox2.getSelectedItem()=="Gigabit Per Second")
{
    String a=jTextField1.getText();
    float a1=Float.parseFloat(a);
double c1=8000*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Terabyte Per Second"&&jComboBox2.getSelectedItem()=="Gigabyte Per Second")
{
    String a=jTextField1.getText();
    float a1=Float.parseFloat(a);
double c1=1000*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Terabyte Per Second"&&jComboBox2.getSelectedItem()=="Gibibit Per Second")
{
    String a=jTextField1.getText();
    float a1=Float.parseFloat(a);
double c1=7450.58*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Terabyte Per Second"&&jComboBox2.getSelectedItem()=="Terabit Per Second")
{
    String a=jTextField1.getText();
    float a1=Float.parseFloat(a);
double c1=8*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Terabyte Per Second"&&jComboBox2.getSelectedItem()=="Terabyte Per Second")
{
    String a=jTextField1.getText();
    float a1=Float.parseFloat(a);
double c1=a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Terabyte Per Second"&&jComboBox2.getSelectedItem()=="Tebibit Per Second")
{
    String a=jTextField1.getText();
    float a1=Float.parseFloat(a);
double c1=7.27596*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Tebibit Per Second"&&jComboBox2.getSelectedItem()=="Bit Per Second")
{
    String a=jTextField1.getText();
    float a1=Float.parseFloat(a);
double c1=1.1e+12*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Tebibit Per Second"&&jComboBox2.getSelectedItem()=="Kilobit Per Second")
{
    String a=jTextField1.getText();
    float a1=Float.parseFloat(a);
double c1=1.1e+9*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Tebibit Per Second"&&jComboBox2.getSelectedItem()=="Kilobyte Per Second")
{
    String a=jTextField1.getText();
    float a1=Float.parseFloat(a);
double c1=1.374e+8*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Tebibit Per Second"&&jComboBox2.getSelectedItem()=="Kibibit Per Second")
{
    String a=jTextField1.getText();
    float a1=Float.parseFloat(a);
double c1=1.074e+9*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Tebibit Per Second"&&jComboBox2.getSelectedItem()=="Megabit Per Second")
{
    String a=jTextField1.getText();
    float a1=Float.parseFloat(a);
double c1=1.1e+6*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Tebibit Per Second"&&jComboBox2.getSelectedItem()=="Megabyte Per Second")
{
    String a=jTextField1.getText();
    float a1=Float.parseFloat(a);
double c1=137439*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Tebibit Per Second"&&jComboBox2.getSelectedItem()=="Mebibit Per Second")
{
    String a=jTextField1.getText();
    float a1=Float.parseFloat(a);
double c1=1.049e+6*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Tebibit Per Second"&&jComboBox2.getSelectedItem()=="Gigabit Per Second")
{
    String a=jTextField1.getText();
    float a1=Float.parseFloat(a);
double c1=1099.51*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Tebibit Per Second"&&jComboBox2.getSelectedItem()=="Gigabyte Per Second")
{
    String a=jTextField1.getText();
    float a1=Float.parseFloat(a);
double c1=137.439*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Tebibit Per Second"&&jComboBox2.getSelectedItem()=="Gibibit Per Second")
{
    String a=jTextField1.getText();
    float a1=Float.parseFloat(a);
double c1=1024*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Tebibit Per Second"&&jComboBox2.getSelectedItem()=="Terabit Per Second")
{
    String a=jTextField1.getText();
    float a1=Float.parseFloat(a);
double c1=1.09951*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Tebibit Per Second"&&jComboBox2.getSelectedItem()=="Terabyte Per Second")
{
    String a=jTextField1.getText();
    float a1=Float.parseFloat(a);
double c1=0.137439*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Tebibit Per Second"&&jComboBox2.getSelectedItem()=="Tebibit Per Second")
{
    String a=jTextField1.getText();
    float a1=Float.parseFloat(a);
double c1=a1;
jTextField2.setText(Double.toString(c1)); 
}


    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
System.exit(0);         // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Data.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Data.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Data.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Data.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Data().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
