/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package converter;

import java.awt.Color;
import static java.awt.Frame.MAXIMIZED_BOTH;

/**
 *
 * @author RAHUL
 */
public class Energy extends javax.swing.JFrame {

    /**
     * Creates new form Energy
     */
    public Energy() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Joule", "Kilojoule", "Gram Calorie", "KiloCalorie", "Watt Hour", "Kilowatt Hour", "Electronvolt", "British Thermal Unit", "US Therm", "Foot-Pound" }));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Joule", "Kilojoule", "Gram Calorie", "KiloCalorie", "Watt Hour", "Kilowatt Hour", "Electronvolt", "British Thermal Unit", "US Therm", "Foot-Pound" }));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setText("MENU");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setText("EXIT");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 153, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ENERGY   CONVERTER");
        jLabel1.setToolTipText("");

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setText("TO");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("-A NOSCIP TECH PRODUCT");

        jLabel3.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("By Hritik jain");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(560, 560, 560)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(258, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addComponent(jButton3)
                        .addGap(156, 156, 156)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(355, 355, 355)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(257, 257, 257))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(95, 95, 95)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(181, 181, 181)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 173, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(137, 137, 137)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
 FrstFrame f= new FrstFrame();
 f.getContentPane().setBackground(Color.DARK_GRAY);
 f.setExtendedState(MAXIMIZED_BOTH);
f.setVisible(true);
this.dispose();           // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
/*Joule
Kilojoule
Gram Calorie
KiloCalorie
Watt Hour
Kilowatt Hour
Electronvolt
British Thermal Unit
US Therm
Foot-Pound*/       if(jComboBox1.getSelectedItem()=="Joule"&&jComboBox2.getSelectedItem()=="Joule")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Joule"&&jComboBox2.getSelectedItem()=="Kilojoule")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=0.001*a1;
jTextField2.setText(Double.toString(c1)); 
}
       else if(jComboBox1.getSelectedItem()=="Joule"&&jComboBox2.getSelectedItem()=="Gram Calorie")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=0.239006*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Joule"&&jComboBox2.getSelectedItem()=="KiloCalorie")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=0.000239006*a1;
jTextField2.setText(Double.toString(c1)); 
}
     else if(jComboBox1.getSelectedItem()=="Joule"&&jComboBox2.getSelectedItem()=="Watt Hour")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=0.000277778*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Joule"&&jComboBox2.getSelectedItem()=="Kilowatt Hour")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=2.7778e-7*a1;
jTextField2.setText(Double.toString(c1)); 
}
     else if(jComboBox1.getSelectedItem()=="Joule"&&jComboBox2.getSelectedItem()=="Electronvolt")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=6.242e+18*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Joule"&&jComboBox2.getSelectedItem()=="British Thermal Unit")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=0.000947817*a1;
jTextField2.setText(Double.toString(c1)); 
}
 else if(jComboBox1.getSelectedItem()=="Joule"&&jComboBox2.getSelectedItem()=="US Therm")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=9.4804e-9*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Joule"&&jComboBox2.getSelectedItem()=="Foot-Pound")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=0.737562*a1;
jTextField2.setText(Double.toString(c1)); 
}
else    if(jComboBox1.getSelectedItem()=="Kilojoule"&&jComboBox2.getSelectedItem()=="Joule")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=1000*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Kilojoule"&&jComboBox2.getSelectedItem()=="Kilojoule")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=a1;
jTextField2.setText(Double.toString(c1)); 
}
       else if(jComboBox1.getSelectedItem()=="Kilojoule"&&jComboBox2.getSelectedItem()=="Gram Calorie")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=239.006*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Kilojoule"&&jComboBox2.getSelectedItem()=="KiloCalorie")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=0.239006*a1;
jTextField2.setText(Double.toString(c1)); 
}
     else if(jComboBox1.getSelectedItem()=="Kilojoule"&&jComboBox2.getSelectedItem()=="Watt Hour")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=0.277778*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Kilojoule"&&jComboBox2.getSelectedItem()=="Kilowatt Hour")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=0.000277778*a1;
jTextField2.setText(Double.toString(c1)); 
}
     else if(jComboBox1.getSelectedItem()=="Kilojoule"&&jComboBox2.getSelectedItem()=="Electronvolt")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=6.242e+21*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Kilojoule"&&jComboBox2.getSelectedItem()=="British Thermal Unit")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=0.947817*a1;
jTextField2.setText(Double.toString(c1)); 
}
 else if(jComboBox1.getSelectedItem()=="Kilojoule"&&jComboBox2.getSelectedItem()=="US Therm")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=9.4804e-6*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Kilojoule"&&jComboBox2.getSelectedItem()=="Foot-Pound")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=737.562*a1;
jTextField2.setText(Double.toString(c1)); 
}
else    if(jComboBox1.getSelectedItem()=="Gram Calorie"&&jComboBox2.getSelectedItem()=="Joule")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=4.184*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Gram Calorie"&&jComboBox2.getSelectedItem()=="Kilojoule")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=0.004184*a1;
jTextField2.setText(Double.toString(c1)); 
}
       else if(jComboBox1.getSelectedItem()=="Gram Calorie"&&jComboBox2.getSelectedItem()=="Gram Calorie")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Gram Calorie"&&jComboBox2.getSelectedItem()=="KiloCalorie")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=0.001*a1;
jTextField2.setText(Double.toString(c1)); 
}
     else if(jComboBox1.getSelectedItem()=="Gram Calorie"&&jComboBox2.getSelectedItem()=="Watt Hour")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=0.00116222*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Gram Calorie"&&jComboBox2.getSelectedItem()=="Kilowatt Hour")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=1.1622e-6*a1;
jTextField2.setText(Double.toString(c1)); 
}
     else if(jComboBox1.getSelectedItem()=="Gram Calorie"&&jComboBox2.getSelectedItem()=="Electronvolt")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=2.611e+19*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Gram Calorie"&&jComboBox2.getSelectedItem()=="British Thermal Unit")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=0.00396567*a1;
jTextField2.setText(Double.toString(c1)); 
}
 else if(jComboBox1.getSelectedItem()=="Gram Calorie"&&jComboBox2.getSelectedItem()=="US Therm")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=3.9666e-8*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Gram Calorie"&&jComboBox2.getSelectedItem()=="Foot-Pound")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=3.08596*a1;
jTextField2.setText(Double.toString(c1)); 
}
else    if(jComboBox1.getSelectedItem()=="KiloCalorie"&&jComboBox2.getSelectedItem()=="Joule")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=4184*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="KiloCalorie"&&jComboBox2.getSelectedItem()=="Kilojoule")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=4.184*a1;
jTextField2.setText(Double.toString(c1)); 
}
       else if(jComboBox1.getSelectedItem()=="KiloCalorie"&&jComboBox2.getSelectedItem()=="Gram Calorie")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=1000*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="KiloCalorie"&&jComboBox2.getSelectedItem()=="KiloCalorie")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=a1;
jTextField2.setText(Double.toString(c1)); 
}
     else if(jComboBox1.getSelectedItem()=="KiloCalorie"&&jComboBox2.getSelectedItem()=="Watt Hour")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=1.16222*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="KiloCalorie"&&jComboBox2.getSelectedItem()=="Kilowatt Hour")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=0.00116222*a1;
jTextField2.setText(Double.toString(c1)); 
}
     else if(jComboBox1.getSelectedItem()=="KiloCalorie"&&jComboBox2.getSelectedItem()=="Electronvolt")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=2.611e+22*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="KiloCalorie"&&jComboBox2.getSelectedItem()=="British Thermal Unit")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=3.96567*a1;
jTextField2.setText(Double.toString(c1)); 
}
 else if(jComboBox1.getSelectedItem()=="KiloCalorie"&&jComboBox2.getSelectedItem()=="US Therm")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=3.9666e-5*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="KiloCalorie"&&jComboBox2.getSelectedItem()=="Foot-Pound")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=3085.96*a1;
jTextField2.setText(Double.toString(c1)); 
}
else    if(jComboBox1.getSelectedItem()=="Watt Hour"&&jComboBox2.getSelectedItem()=="Joule")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=3600*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Watt Hour"&&jComboBox2.getSelectedItem()=="Kilojoule")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=3.6*a1;
jTextField2.setText(Double.toString(c1)); 
}
       else if(jComboBox1.getSelectedItem()=="Watt Hour"&&jComboBox2.getSelectedItem()=="Gram Calorie")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=860.421*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Watt Hour"&&jComboBox2.getSelectedItem()=="KiloCalorie")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=0.860421*a1;
jTextField2.setText(Double.toString(c1)); 
}
     else if(jComboBox1.getSelectedItem()=="Watt Hour"&&jComboBox2.getSelectedItem()=="Watt Hour")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Watt Hour"&&jComboBox2.getSelectedItem()=="Kilowatt Hour")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=0.001*a1;
jTextField2.setText(Double.toString(c1)); 
}
     else if(jComboBox1.getSelectedItem()=="Watt Hour"&&jComboBox2.getSelectedItem()=="Electronvolt")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=2.247e+22*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Watt Hour"&&jComboBox2.getSelectedItem()=="British Thermal Unit")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=3.41214*a1;
jTextField2.setText(Double.toString(c1)); 
}
 else if(jComboBox1.getSelectedItem()=="Watt Hour"&&jComboBox2.getSelectedItem()=="US Therm")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=3.413e-5*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Watt Hour"&&jComboBox2.getSelectedItem()=="Foot-Pound")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=2655.22*a1;
jTextField2.setText(Double.toString(c1)); 
}
else    if(jComboBox1.getSelectedItem()=="Kilowatt Hour"&&jComboBox2.getSelectedItem()=="Joule")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=3.6e+6*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Kilowatt Hour"&&jComboBox2.getSelectedItem()=="Kilojoule")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=3.6e+3*a1;
jTextField2.setText(Double.toString(c1)); 
}
       else if(jComboBox1.getSelectedItem()=="Kilowatt Hour"&&jComboBox2.getSelectedItem()=="Gram Calorie")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=860421*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Kilowatt Hour"&&jComboBox2.getSelectedItem()=="KiloCalorie")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=860.421*a1;
jTextField2.setText(Double.toString(c1)); 
}
     else if(jComboBox1.getSelectedItem()=="Kilowatt Hour"&&jComboBox2.getSelectedItem()=="Watt Hour")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=1000*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Kilowatt Hour"&&jComboBox2.getSelectedItem()=="Kilowatt Hour")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=a1;
jTextField2.setText(Double.toString(c1)); 
}
     else if(jComboBox1.getSelectedItem()=="Kilowatt Hour"&&jComboBox2.getSelectedItem()=="Electronvolt")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=2.247e+25*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Kilowatt Hour"&&jComboBox2.getSelectedItem()=="British Thermal Unit")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=3412.14*a1;
jTextField2.setText(Double.toString(c1)); 
}
 else if(jComboBox1.getSelectedItem()=="Kilowatt Hour"&&jComboBox2.getSelectedItem()=="US Therm")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=0.0341296*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Kilowatt Hour"&&jComboBox2.getSelectedItem()=="Foot-Pound")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=2.655e+6*a1;
jTextField2.setText(Double.toString(c1)); 
}
else    if(jComboBox1.getSelectedItem()=="Electronvolt"&&jComboBox2.getSelectedItem()=="Joule")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=1.6022e-19*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Electronvolt"&&jComboBox2.getSelectedItem()=="Kilojoule")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=1.6022e-22*a1;
jTextField2.setText(Double.toString(c1)); 
}
       else if(jComboBox1.getSelectedItem()=="Electronvolt"&&jComboBox2.getSelectedItem()=="Gram Calorie")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=3.8293e-20*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Electronvolt"&&jComboBox2.getSelectedItem()=="KiloCalorie")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=3.8293e-23*a1;
jTextField2.setText(Double.toString(c1)); 
}
     else if(jComboBox1.getSelectedItem()=="Electronvolt"&&jComboBox2.getSelectedItem()=="Watt Hour")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=4.4505e-23*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Electronvolt"&&jComboBox2.getSelectedItem()=="Kilowatt Hour")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=4.4505e-26*a1;
jTextField2.setText(Double.toString(c1)); 
}
     else if(jComboBox1.getSelectedItem()=="Electronvolt"&&jComboBox2.getSelectedItem()=="Electronvolt")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Electronvolt"&&jComboBox2.getSelectedItem()=="British Thermal Unit")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=1.5186e-22*a1;
jTextField2.setText(Double.toString(c1)); 
}
 else if(jComboBox1.getSelectedItem()=="Electronvolt"&&jComboBox2.getSelectedItem()=="US Therm")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=1.5189e-27*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Electronvolt"&&jComboBox2.getSelectedItem()=="Foot-Pound")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=1.1817e-19*a1;
jTextField2.setText(Double.toString(c1)); 
}
else    if(jComboBox1.getSelectedItem()=="British Thermal Unit"&&jComboBox2.getSelectedItem()=="Joule")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=1055.06*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="British Thermal Unit"&&jComboBox2.getSelectedItem()=="Kilojoule")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=1.05506*a1;
jTextField2.setText(Double.toString(c1)); 
}
       else if(jComboBox1.getSelectedItem()=="British Thermal Unit"&&jComboBox2.getSelectedItem()=="Gram Calorie")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=252.164*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="British Thermal Unit"&&jComboBox2.getSelectedItem()=="KiloCalorie")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=0.252164*a1;
jTextField2.setText(Double.toString(c1)); 
}
     else if(jComboBox1.getSelectedItem()=="British Thermal Unit"&&jComboBox2.getSelectedItem()=="Watt Hour")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=0.293071*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="British Thermal Unit"&&jComboBox2.getSelectedItem()=="Kilowatt Hour")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=0.000293071*a1;
jTextField2.setText(Double.toString(c1)); 
}
     else if(jComboBox1.getSelectedItem()=="British Thermal Unit"&&jComboBox2.getSelectedItem()=="Electronvolt")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=6.585e+21*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="British Thermal Unit"&&jComboBox2.getSelectedItem()=="British Thermal Unit")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=a1;
jTextField2.setText(Double.toString(c1)); 
}
 else if(jComboBox1.getSelectedItem()=="British Thermal Unit"&&jComboBox2.getSelectedItem()=="US Therm")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=1.0002e-5*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="British Thermal Unit"&&jComboBox2.getSelectedItem()=="Foot-Pound")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=778.169*a1;
jTextField2.setText(Double.toString(c1)); 
}
else    if(jComboBox1.getSelectedItem()=="US Therm"&&jComboBox2.getSelectedItem()=="Joule")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=1.055e+8*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="US Therm"&&jComboBox2.getSelectedItem()=="Kilojoule")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=1.055e+5*a1;
jTextField2.setText(Double.toString(c1)); 
}
       else if(jComboBox1.getSelectedItem()=="US Therm"&&jComboBox2.getSelectedItem()=="Gram Calorie")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=2.521e+7*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="US Therm"&&jComboBox2.getSelectedItem()=="KiloCalorie")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=2.521e+4*a1;
jTextField2.setText(Double.toString(c1)); 
}
     else if(jComboBox1.getSelectedItem()=="US Therm"&&jComboBox2.getSelectedItem()=="Watt Hour")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=29300.1*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="US Therm"&&jComboBox2.getSelectedItem()=="Kilowatt Hour")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=29.3001*a1;
jTextField2.setText(Double.toString(c1)); 
}
     else if(jComboBox1.getSelectedItem()=="US Therm"&&jComboBox2.getSelectedItem()=="Electronvolt")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=6.584e+26*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="US Therm"&&jComboBox2.getSelectedItem()=="British Thermal Unit")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=99976.1*a1;
jTextField2.setText(Double.toString(c1)); 
}
 else if(jComboBox1.getSelectedItem()=="US Therm"&&jComboBox2.getSelectedItem()=="US Therm")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="US Therm"&&jComboBox2.getSelectedItem()=="Foot-Pound")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=7.78e+7*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Foot-Pound"&&jComboBox2.getSelectedItem()=="Joule")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=1.35582*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Foot-Pound"&&jComboBox2.getSelectedItem()=="Kilojoule")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=0.00135582*a1;
jTextField2.setText(Double.toString(c1)); 
}
       else if(jComboBox1.getSelectedItem()=="Foot-Pound"&&jComboBox2.getSelectedItem()=="Gram Calorie")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=0.324048*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Foot-Pound"&&jComboBox2.getSelectedItem()=="KiloCalorie")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=0.000324048*a1;
jTextField2.setText(Double.toString(c1)); 
}
     else if(jComboBox1.getSelectedItem()=="Foot-Pound"&&jComboBox2.getSelectedItem()=="Watt Hour")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=0.000376616*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Foot-Pound"&&jComboBox2.getSelectedItem()=="Kilowatt Hour")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=3.7662e-7*a1;
jTextField2.setText(Double.toString(c1)); 
}
     else if(jComboBox1.getSelectedItem()=="Foot-Pound"&&jComboBox2.getSelectedItem()=="Electronvolt")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=8.462e+18*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Foot-Pound"&&jComboBox2.getSelectedItem()=="British Thermal Unit")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=0.00128507*a1;
jTextField2.setText(Double.toString(c1)); 
}
 else if(jComboBox1.getSelectedItem()=="Foot-Pound"&&jComboBox2.getSelectedItem()=="US Therm")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=1.2854e-8*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Foot-Pound"&&jComboBox2.getSelectedItem()=="Foot-Pound")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=7.78e+7*a1;
jTextField2.setText(Double.toString(c1)); 
}

// TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
System.exit(0);         // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Energy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Energy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Energy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Energy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Energy().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
