/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package converter;

import java.awt.Color;
import static java.awt.Frame.MAXIMIZED_BOTH;

/**
 *
 * @author RAHUL
 */
public class FrstFrame extends javax.swing.JFrame {

    /**
     * Creates new form FrstFrame
     */
    public FrstFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jComboBox1.setMaximumRowCount(15);
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AREA", "DATA TRANSFER RATE", "DIGITAL STORAGE", "ENERGY", "FREQUENCY", "FUEL ECONOMY", "LENGTH", "MASS", "PLANE ANGLE", "PRESSURE", "SPEED", "TEMPERATURE", "TIME", "VOLUME" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("UNIT  CONVERTER");

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setText("EXIT");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("-A NOSCIP TECH PRODUCT");

        jLabel3.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("By Hritik jain");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(374, 374, 374)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 594, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(194, 194, 194)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(576, 576, 576)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(382, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(134, 134, 134)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(121, 121, 121)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 192, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(90, 90, 90)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       if(jComboBox1.getSelectedItem()=="AREA")
       { Area a=new Area();
       a.getContentPane().setBackground(Color.DARK_GRAY);
       a.setExtendedState(MAXIMIZED_BOTH);
       a.setVisible(true);this.dispose();
       }
        else if(jComboBox1.getSelectedItem()=="DATA TRANSFER RATE")
       { Data a=new Data();
       a.getContentPane().setBackground(Color.DARK_GRAY);
       a.setExtendedState(MAXIMIZED_BOTH);
       a.setVisible(true);this.dispose();
       }
        else if(jComboBox1.getSelectedItem()=="DIGITAL STORAGE")
       { Digit a=new Digit();
       a.setExtendedState(MAXIMIZED_BOTH);
        a.getContentPane().setBackground(Color.DARK_GRAY);
       a.setVisible(true);this.dispose();
       }
        else if(jComboBox1.getSelectedItem()=="ENERGY")
       { Energy a=new Energy();
       a.setExtendedState(MAXIMIZED_BOTH);
        a.getContentPane().setBackground(Color.DARK_GRAY);
       a.setVisible(true);this.dispose();
       } 
        else if(jComboBox1.getSelectedItem()=="FREQUENCY")
       { Frequency a=new Frequency();
       a.setExtendedState(MAXIMIZED_BOTH);
        a.getContentPane().setBackground(Color.DARK_GRAY);
       a.setVisible(true);this.dispose();
       }   
          else if(jComboBox1.getSelectedItem()=="FUEL ECONOMY")
       { Fuel a=new Fuel();
       a.setExtendedState(MAXIMIZED_BOTH);
        a.getContentPane().setBackground(Color.DARK_GRAY);
       a.setVisible(true);this.dispose();
       } 
          else if(jComboBox1.getSelectedItem()=="LENGTH")
       { Length a=new Length();
       a.setExtendedState(MAXIMIZED_BOTH);
        a.getContentPane().setBackground(Color.DARK_GRAY);
       a.setVisible(true);this.dispose();
       } 
          else if(jComboBox1.getSelectedItem()=="MASS")
       { Mass a=new Mass();
       a.setExtendedState(MAXIMIZED_BOTH);
        a.getContentPane().setBackground(Color.DARK_GRAY);
       a.setVisible(true);this.dispose();
       } 
          else if(jComboBox1.getSelectedItem()=="PLANE ANGLE")
       { PlaneAngle a=new PlaneAngle();
       a.setExtendedState(MAXIMIZED_BOTH);
        a.getContentPane().setBackground(Color.DARK_GRAY);
       a.setVisible(true);this.dispose();
       } 
          else if(jComboBox1.getSelectedItem()=="PRESSURE")
       { Pressure a=new Pressure();
       a.setExtendedState(MAXIMIZED_BOTH);
        a.getContentPane().setBackground(Color.DARK_GRAY);
       a.setVisible(true);this.dispose();
       } 
          else if(jComboBox1.getSelectedItem()=="SPEED")
       { Speed a=new Speed();
       a.setExtendedState(MAXIMIZED_BOTH);
        a.getContentPane().setBackground(Color.DARK_GRAY);
       a.setVisible(true);this.dispose();
       } 
            else if(jComboBox1.getSelectedItem()=="TEMPERATURE")
       { Temperature a=new Temperature();
       a.setExtendedState(MAXIMIZED_BOTH);
        a.getContentPane().setBackground(Color.DARK_GRAY);
       a.setVisible(true);this.dispose();
       } 
            else if(jComboBox1.getSelectedItem()=="TIME")
       { Time a=new Time();
       a.setExtendedState(MAXIMIZED_BOTH);
        a.getContentPane().setBackground(Color.DARK_GRAY);
       a.setVisible(true);this.dispose();
       } 
            else if(jComboBox1.getSelectedItem()=="VOLUME")
       { Volume a=new Volume();
       a.setExtendedState(MAXIMIZED_BOTH);
        a.getContentPane().setBackground(Color.DARK_GRAY);
       a.setVisible(true);this.dispose();
       } 
// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
System.exit(0);         // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrstFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrstFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrstFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrstFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FrstFrame f= new FrstFrame();
 f.getContentPane().setBackground(Color.DARK_GRAY);
 f.setExtendedState(MAXIMIZED_BOTH);
f.setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
