/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package converter;

import java.awt.Color;
import static java.awt.Frame.MAXIMIZED_BOTH;

/**
 *
 * @author RAHUL
 */
public class Length extends javax.swing.JFrame {

    /**
     * Creates new form Length
     */
    public Length() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Kilometre", "Metre", "Centimetre", "Millimetre", "Micrometre", "Nanometre", "Mile", "Yard", "Foot", "Inch", "Nautical Mile" }));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Kilometre", "Metre", "Centimetre", "Millimetre", "Micrometre", "Nanometre", "Mile", "Yard", "Foot", "Inch", "Nautical Mile" }));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setText("MENU");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setText("EXIT");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 255, 51));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("LENGTH  CONVERTER");
        jLabel1.setToolTipText("");

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setText("TO");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("-A NOSCIP TECH PRODUCT");

        jLabel3.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("By Hritik jain");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(573, 573, 573)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(255, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(349, 349, 349))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton3)
                        .addGap(147, 147, 147)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(254, 254, 254))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(95, 95, 95)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(181, 181, 181)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 173, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(137, 137, 137)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
 FrstFrame f= new FrstFrame();
 f.getContentPane().setBackground(Color.DARK_GRAY);
 f.setExtendedState(MAXIMIZED_BOTH);
f.setVisible(true);
this.dispose();          // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
/*Kilometre
Metre
Centimetre
Millimetre
Micrometre
Nanometre
Mile
Yard
Foot
Inch
Nautical Mile*/
if(jComboBox1.getSelectedItem()=="Kilometre"&&jComboBox2.getSelectedItem()=="Kilometre")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Kilometre"&&jComboBox2.getSelectedItem()=="Metre")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=1000*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Kilometre"&&jComboBox2.getSelectedItem()=="Centimetre")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=100000*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Kilometre"&&jComboBox2.getSelectedItem()=="Millimetre")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=1000000*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Kilometre"&&jComboBox2.getSelectedItem()=="Micrometre")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=1e+9*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Kilometre"&&jComboBox2.getSelectedItem()=="Nanometre")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=1e+12*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Kilometre"&&jComboBox2.getSelectedItem()=="Mile")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=0.621371*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Kilometre"&&jComboBox2.getSelectedItem()=="Yard")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=1093.61*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Kilometre"&&jComboBox2.getSelectedItem()=="Foot")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=3280.84*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Kilometre"&&jComboBox2.getSelectedItem()=="Inch")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=39370.1*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Kilometre"&&jComboBox2.getSelectedItem()=="Nautical Mile")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=0.539957*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Metre"&&jComboBox2.getSelectedItem()=="Kilometre")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=0.001*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Metre"&&jComboBox2.getSelectedItem()=="Metre")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Metre"&&jComboBox2.getSelectedItem()=="Centimetre")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=100*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Metre"&&jComboBox2.getSelectedItem()=="Millimetre")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=1000*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Metre"&&jComboBox2.getSelectedItem()=="Micrometre")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=1e+6*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Metre"&&jComboBox2.getSelectedItem()=="Nanometre")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=1e+9*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Metre"&&jComboBox2.getSelectedItem()=="Mile")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=0.000621371*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Metre"&&jComboBox2.getSelectedItem()=="Yard")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=1.09361*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Metre"&&jComboBox2.getSelectedItem()=="Foot")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=3.28084*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Metre"&&jComboBox2.getSelectedItem()=="Inch")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=39.3701*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Metre"&&jComboBox2.getSelectedItem()=="Nautical Mile")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=0.000539957*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Centimetre"&&jComboBox2.getSelectedItem()=="Kilometre")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=1e-5*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Centimetre"&&jComboBox2.getSelectedItem()=="Metre")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=0.01*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Centimetre"&&jComboBox2.getSelectedItem()=="Centimetre")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Centimetre"&&jComboBox2.getSelectedItem()=="Millimetre")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=10*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Centimetre"&&jComboBox2.getSelectedItem()=="Micrometre")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=10000*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Centimetre"&&jComboBox2.getSelectedItem()=="Nanometre")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=1e+7*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Centimetre"&&jComboBox2.getSelectedItem()=="Mile")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=6.2137e-6*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Centimetre"&&jComboBox2.getSelectedItem()=="Yard")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=0.0109361*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Centimetre"&&jComboBox2.getSelectedItem()=="Foot")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=0.0328084*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Centimetre"&&jComboBox2.getSelectedItem()=="Inch")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=0.393701*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Centimetre"&&jComboBox2.getSelectedItem()=="Nautical Mile")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=5.3996e-6*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Millimetre"&&jComboBox2.getSelectedItem()=="Kilometre")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=1e-6*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Millimetre"&&jComboBox2.getSelectedItem()=="Metre")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=0.001*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Millimetre"&&jComboBox2.getSelectedItem()=="Centimetre")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=.1*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Millimetre"&&jComboBox2.getSelectedItem()=="Millimetre")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Millimetre"&&jComboBox2.getSelectedItem()=="Micrometre")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=1000*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Millimetre"&&jComboBox2.getSelectedItem()=="Nanometre")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=1000000*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Millimetre"&&jComboBox2.getSelectedItem()=="Mile")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=6.2137e-7*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Millimetre"&&jComboBox2.getSelectedItem()=="Yard")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=0.00109361*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Millimetre"&&jComboBox2.getSelectedItem()=="Foot")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=0.00328084*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Millimetre"&&jComboBox2.getSelectedItem()=="Inch")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=0.0393701*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Millimetre"&&jComboBox2.getSelectedItem()=="Nautical Mile")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=5.3996e-7*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Micrometre"&&jComboBox2.getSelectedItem()=="Kilometre")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=1e-9*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Micrometre"&&jComboBox2.getSelectedItem()=="Metre")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=1e-6*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Micrometre"&&jComboBox2.getSelectedItem()=="Centimetre")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=1e-4*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Micrometre"&&jComboBox2.getSelectedItem()=="Millimetre")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=0.001*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Micrometre"&&jComboBox2.getSelectedItem()=="Micrometre")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Micrometre"&&jComboBox2.getSelectedItem()=="Nanometre")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=1000*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Micrometre"&&jComboBox2.getSelectedItem()=="Mile")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=6.2137e-10*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Micrometre"&&jComboBox2.getSelectedItem()=="Yard")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=1.0936e-6*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Micrometre"&&jComboBox2.getSelectedItem()=="Foot")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=3.2808e-6*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Micrometre"&&jComboBox2.getSelectedItem()=="Inch")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=3.937e-5*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Micrometre"&&jComboBox2.getSelectedItem()=="Nautical Mile")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=5.3996e-10*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Nanometre"&&jComboBox2.getSelectedItem()=="Kilometre")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=1e-12*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Nanometre"&&jComboBox2.getSelectedItem()=="Metre")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=1e-9*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Nanometre"&&jComboBox2.getSelectedItem()=="Centimetre")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=1e-7*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Nanometre"&&jComboBox2.getSelectedItem()=="Millimetre")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=1e-6*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Nanometre"&&jComboBox2.getSelectedItem()=="Micrometre")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=0.001*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Nanometre"&&jComboBox2.getSelectedItem()=="Nanometre")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Nanometre"&&jComboBox2.getSelectedItem()=="Mile")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=6.2137e-13*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Nanometre"&&jComboBox2.getSelectedItem()=="Yard")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=1.0936e-9*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Nanometre"&&jComboBox2.getSelectedItem()=="Foot")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=3.2808e-9*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Nanometre"&&jComboBox2.getSelectedItem()=="Inch")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=3.937e-8*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Nanometre"&&jComboBox2.getSelectedItem()=="Nautical Mile")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=5.3996e-13*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Mile"&&jComboBox2.getSelectedItem()=="Kilometre")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=1.60934*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Mile"&&jComboBox2.getSelectedItem()=="Metre")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=1609.34*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Mile"&&jComboBox2.getSelectedItem()=="Centimetre")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=160934*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Mile"&&jComboBox2.getSelectedItem()=="Millimetre")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=1.609e+6*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Mile"&&jComboBox2.getSelectedItem()=="Micrometre")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=1.609e+9*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Mile"&&jComboBox2.getSelectedItem()=="Nanometre")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=1.609e+12*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Mile"&&jComboBox2.getSelectedItem()=="Mile")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Mile"&&jComboBox2.getSelectedItem()=="Yard")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=1760*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Mile"&&jComboBox2.getSelectedItem()=="Foot")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=5820*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Mile"&&jComboBox2.getSelectedItem()=="Inch")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=63360*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Mile"&&jComboBox2.getSelectedItem()=="Nautical Mile")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=0.868976*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Yard"&&jComboBox2.getSelectedItem()=="Kilometre")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=0.0009144*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Yard"&&jComboBox2.getSelectedItem()=="Metre")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=0.9144*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Yard"&&jComboBox2.getSelectedItem()=="Centimetre")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=91.44*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Yard"&&jComboBox2.getSelectedItem()=="Millimetre")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=914.4*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Yard"&&jComboBox2.getSelectedItem()=="Micrometre")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=914400*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Yard"&&jComboBox2.getSelectedItem()=="Nanometre")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=9.144e+8*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Yard"&&jComboBox2.getSelectedItem()=="Mile")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=0.000568182*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Yard"&&jComboBox2.getSelectedItem()=="Yard")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Yard"&&jComboBox2.getSelectedItem()=="Foot")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=3*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Yard"&&jComboBox2.getSelectedItem()=="Inch")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=36*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Yard"&&jComboBox2.getSelectedItem()=="Nautical Mile")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=0.000493737*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Foot"&&jComboBox2.getSelectedItem()=="Kilometre")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=0.0003048*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Foot"&&jComboBox2.getSelectedItem()=="Metre")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=0.3048*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Foot"&&jComboBox2.getSelectedItem()=="Centimetre")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=30.48*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Foot"&&jComboBox2.getSelectedItem()=="Millimetre")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=304.8*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Foot"&&jComboBox2.getSelectedItem()=="Micrometre")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=304800*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Foot"&&jComboBox2.getSelectedItem()=="Nanometre")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=3.048e+8*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Foot"&&jComboBox2.getSelectedItem()=="Mile")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=0.000189394*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Foot"&&jComboBox2.getSelectedItem()=="Yard")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=0.333333*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Foot"&&jComboBox2.getSelectedItem()=="Foot")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Foot"&&jComboBox2.getSelectedItem()=="Inch")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=12*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Foot"&&jComboBox2.getSelectedItem()=="Nautical Mile")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=0.000164579*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Inch"&&jComboBox2.getSelectedItem()=="Kilometre")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=2.54e-5*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Inch"&&jComboBox2.getSelectedItem()=="Metre")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=0.0254*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Inch"&&jComboBox2.getSelectedItem()=="Centimetre")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=2.54*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Inch"&&jComboBox2.getSelectedItem()=="Millimetre")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=25.4*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Inch"&&jComboBox2.getSelectedItem()=="Micrometre")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=25400*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Inch"&&jComboBox2.getSelectedItem()=="Nanometre")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=2.54e+7*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Inch"&&jComboBox2.getSelectedItem()=="Mile")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=1.5783e-5*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Inch"&&jComboBox2.getSelectedItem()=="Yard")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=0.0277778*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Inch"&&jComboBox2.getSelectedItem()=="Foot")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=0.0833333*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Inch"&&jComboBox2.getSelectedItem()=="Inch")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Inch"&&jComboBox2.getSelectedItem()=="Nautical Mile")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=1.3715e-5*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Nautical Mile"&&jComboBox2.getSelectedItem()=="Kilometre")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=1.852*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Nautical Mile"&&jComboBox2.getSelectedItem()=="Metre")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=1852*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Nautical Mile"&&jComboBox2.getSelectedItem()=="Centimetre")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=185200*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Nautical Mile"&&jComboBox2.getSelectedItem()=="Millimetre")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=1.852e+6*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Nautical Mile"&&jComboBox2.getSelectedItem()=="Micrometre")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=1.852e+9*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Nautical Mile"&&jComboBox2.getSelectedItem()=="Nanometre")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=1.852e+12*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Nautical Mile"&&jComboBox2.getSelectedItem()=="Mile")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=1.15078*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Nautical Mile"&&jComboBox2.getSelectedItem()=="Yard")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=2025.37*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Nautical Mile"&&jComboBox2.getSelectedItem()=="Foot")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=6076.12*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Nautical Mile"&&jComboBox2.getSelectedItem()=="Inch")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=72913.4*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Nautical Mile"&&jComboBox2.getSelectedItem()=="Nautical Mile")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=a1;
jTextField2.setText(Double.toString(c1)); 
} 
 
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
System.exit(0);         // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Length.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Length.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Length.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Length.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Length().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
