/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package converter;

import java.awt.Color;
import static java.awt.Frame.MAXIMIZED_BOTH;

/**
 *
 * @author RAHUL
 */
public class Pressure extends javax.swing.JFrame {

    /**
     * Creates new form Pressure
     */
    public Pressure() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jComboBox2 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Atomosphere", "Bar", "Pascal", "Pound-Force Per Square Inch", "Torr" }));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setText("MENU");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setText("EXIT");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("PRESSURE   CONVERTER");
        jLabel1.setToolTipText("");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Atomosphere", "Bar", "Pascal", "Pound-Force Per Square Inch", "Torr" }));

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setText("TO");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("-A NOSCIP TECH PRODUCT");

        jLabel3.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("By Hritik jain");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(181, 181, 181)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(218, 218, 218)
                        .addComponent(jLabel1)
                        .addGap(563, 563, 563))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(172, 172, 172)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(130, 130, 130)
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(175, 175, 175))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(100, 100, 100)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(176, 176, 176)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 173, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton1))
                .addGap(137, 137, 137)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
 FrstFrame f= new FrstFrame();
 f.getContentPane().setBackground(Color.DARK_GRAY);
 f.setExtendedState(MAXIMIZED_BOTH);
f.setVisible(true);
this.dispose();      // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
/*Atomosphere
Bar
Pascal
Pound-Force Per Square Inch
Torr*/
 if(jComboBox1.getSelectedItem()=="Atomosphere"&&jComboBox2.getSelectedItem()=="Atomosphere")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=a1;
jTextField2.setText(Double.toString(c1)); 
}
 else  if(jComboBox1.getSelectedItem()=="Atomosphere"&&jComboBox2.getSelectedItem()=="Bar")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=1.01325*a1;
jTextField2.setText(Double.toString(c1)); 
}
 else  if(jComboBox1.getSelectedItem()=="Atomosphere"&&jComboBox2.getSelectedItem()=="Pascal")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=101325*a1;
jTextField2.setText(Double.toString(c1)); 
}
 else  if(jComboBox1.getSelectedItem()=="Atomosphere"&&jComboBox2.getSelectedItem()=="Pound-Force Per Square Inch")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=14.6959*a1;
jTextField2.setText(Double.toString(c1)); 
}
 else  if(jComboBox1.getSelectedItem()=="Atomosphere"&&jComboBox2.getSelectedItem()=="Torr")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=760*a1;
jTextField2.setText(Double.toString(c1)); 
}
 
 else if(jComboBox1.getSelectedItem()=="Bar"&&jComboBox2.getSelectedItem()=="Atomosphere")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=0.986923*a1;
jTextField2.setText(Double.toString(c1)); 
}
 else  if(jComboBox1.getSelectedItem()=="Bar"&&jComboBox2.getSelectedItem()=="Bar")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=a1;
jTextField2.setText(Double.toString(c1)); 
}
 else  if(jComboBox1.getSelectedItem()=="Bar"&&jComboBox2.getSelectedItem()=="Pascal")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=100000*a1;
jTextField2.setText(Double.toString(c1)); 
}
 else  if(jComboBox1.getSelectedItem()=="Bar"&&jComboBox2.getSelectedItem()=="Pound-Force Per Square Inch")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=14.5038*a1;
jTextField2.setText(Double.toString(c1)); 
}
 else  if(jComboBox1.getSelectedItem()=="Bar"&&jComboBox2.getSelectedItem()=="Torr")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=750.062*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Pascal"&&jComboBox2.getSelectedItem()=="Atomosphere")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=9.8692e-6*a1;
jTextField2.setText(Double.toString(c1)); 
}
 else  if(jComboBox1.getSelectedItem()=="Pascal"&&jComboBox2.getSelectedItem()=="Bar")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=1e-5*a1;
jTextField2.setText(Double.toString(c1)); 
}
 else  if(jComboBox1.getSelectedItem()=="Pascal"&&jComboBox2.getSelectedItem()=="Pascal")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=a1;
jTextField2.setText(Double.toString(c1)); 
}
 else  if(jComboBox1.getSelectedItem()=="Pascal"&&jComboBox2.getSelectedItem()=="Pound-Force Per Square Inch")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=0.000145038*a1;
jTextField2.setText(Double.toString(c1)); 
}
 else  if(jComboBox1.getSelectedItem()=="Pascal"&&jComboBox2.getSelectedItem()=="Torr")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=0.00750062*a1;
jTextField2.setText(Double.toString(c1)); 
}
 else if(jComboBox1.getSelectedItem()=="Pound-Force Per Square Inch"&&jComboBox2.getSelectedItem()=="Atomosphere")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=0.068046*a1;
jTextField2.setText(Double.toString(c1)); 
}
 else  if(jComboBox1.getSelectedItem()=="Pound-Force Per Square Inch"&&jComboBox2.getSelectedItem()=="Bar")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=0.0689476*a1;
jTextField2.setText(Double.toString(c1)); 
}
 else  if(jComboBox1.getSelectedItem()=="Pound-Force Per Square Inch"&&jComboBox2.getSelectedItem()=="Pascal")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=6894.76*a1;
jTextField2.setText(Double.toString(c1)); 
}
 else  if(jComboBox1.getSelectedItem()=="Pound-Force Per Square Inch"&&jComboBox2.getSelectedItem()=="Pound-Force Per Square Inch")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=a1;
jTextField2.setText(Double.toString(c1)); 
}
 else  if(jComboBox1.getSelectedItem()=="Pound-Force Per Square Inch"&&jComboBox2.getSelectedItem()=="Torr")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=51.7149*a1;
jTextField2.setText(Double.toString(c1)); 
}
 else if(jComboBox1.getSelectedItem()=="Torr"&&jComboBox2.getSelectedItem()=="Atomosphere")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=0.00131579*a1;
jTextField2.setText(Double.toString(c1)); 
}
 else  if(jComboBox1.getSelectedItem()=="Torr"&&jComboBox2.getSelectedItem()=="Bar")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=0.00133322*a1;
jTextField2.setText(Double.toString(c1)); 
}
 else  if(jComboBox1.getSelectedItem()=="Torr"&&jComboBox2.getSelectedItem()=="Pascal")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=133.322*a1;
jTextField2.setText(Double.toString(c1)); 
}
 else  if(jComboBox1.getSelectedItem()=="Torr"&&jComboBox2.getSelectedItem()=="Pound-Force Per Square Inch")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=0.0193368*a1;
jTextField2.setText(Double.toString(c1)); 
}
 else  if(jComboBox1.getSelectedItem()=="Torr"&&jComboBox2.getSelectedItem()=="Torr")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=a1;
jTextField2.setText(Double.toString(c1)); 
}

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pressure.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pressure.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pressure.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pressure.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pressure().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
