/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package converter;

import java.awt.Color;
import static java.awt.Frame.MAXIMIZED_BOTH;

/**
 *
 * @author RAHUL
 */
public class Speed extends javax.swing.JFrame {

    /**
     * Creates new form Speed
     */
    public Speed() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Miles Per Hour", "Foot Per Second", "Metre Per Second", "Kilometre Per Hour", "Knot" }));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Miles Per Hour", "Foot Per Second", "Metre Per Second", "Kilometre Per Hour", "Knot" }));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setText("MENU");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setText("EXIT");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 102));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("SPEED  CONVERTER");
        jLabel1.setToolTipText("");

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setText("TO");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("-A NOSCIP TECH PRODUCT");

        jLabel3.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("By Hritik jain");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(254, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(198, 198, 198)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(148, 148, 148)
                                .addComponent(jButton3)
                                .addGap(148, 148, 148)
                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(254, 254, 254))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(94, 94, 94)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(182, 182, 182)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 173, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton1))
                .addGap(137, 137, 137)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
 FrstFrame f= new FrstFrame();
 f.getContentPane().setBackground(Color.DARK_GRAY);
 f.setExtendedState(MAXIMIZED_BOTH);
f.setVisible(true);
this.dispose();         // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
/*Miles Per Hour
Foot Per Second
Metre Per Second
Kilometre Per Hour
Knot*/
if(jComboBox1.getSelectedItem()=="Miles Per Hour"&&jComboBox2.getSelectedItem()=="Miles Per Hour")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=a1;
jTextField2.setText(Double.toString(c1)); 
}
 else  if(jComboBox1.getSelectedItem()=="Miles Per Hour"&&jComboBox2.getSelectedItem()=="Foot Per Second")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=1.46667*a1;
jTextField2.setText(Double.toString(c1)); 
}
 else  if(jComboBox1.getSelectedItem()=="Miles Per Hour"&&jComboBox2.getSelectedItem()=="Metre Per Second")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=0.44704*a1;
jTextField2.setText(Double.toString(c1)); 
}
 else  if(jComboBox1.getSelectedItem()=="Miles Per Hour"&&jComboBox2.getSelectedItem()=="Kilometre Per Hour")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=1.60934*a1;
jTextField2.setText(Double.toString(c1)); 
}
 else  if(jComboBox1.getSelectedItem()=="Miles Per Hour"&&jComboBox2.getSelectedItem()=="Knot")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=0.868976*a1;
jTextField2.setText(Double.toString(c1)); 
}
 
 else if(jComboBox1.getSelectedItem()=="Foot Per Second"&&jComboBox2.getSelectedItem()=="Miles Per Hour")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=0.681818*a1;
jTextField2.setText(Double.toString(c1)); 
}
 else  if(jComboBox1.getSelectedItem()=="Foot Per Second"&&jComboBox2.getSelectedItem()=="Foot Per Second")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=a1;
jTextField2.setText(Double.toString(c1)); 
}
 else  if(jComboBox1.getSelectedItem()=="Foot Per Second"&&jComboBox2.getSelectedItem()=="Metre Per Second")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=0.3048*a1;
jTextField2.setText(Double.toString(c1)); 
}
 else  if(jComboBox1.getSelectedItem()=="Foot Per Second"&&jComboBox2.getSelectedItem()=="Kilometre Per Hour")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=1.09728*a1;
jTextField2.setText(Double.toString(c1)); 
}
 else  if(jComboBox1.getSelectedItem()=="Foot Per Second"&&jComboBox2.getSelectedItem()=="Knot")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=0.592484*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Metre Per Second"&&jComboBox2.getSelectedItem()=="Miles Per Hour")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=2.23694*a1;
jTextField2.setText(Double.toString(c1)); 
}
 else  if(jComboBox1.getSelectedItem()=="Metre Per Second"&&jComboBox2.getSelectedItem()=="Foot Per Second")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=3.28084*a1;
jTextField2.setText(Double.toString(c1)); 
}
 else  if(jComboBox1.getSelectedItem()=="Metre Per Second"&&jComboBox2.getSelectedItem()=="Metre Per Second")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=a1;
jTextField2.setText(Double.toString(c1)); 
}
 else  if(jComboBox1.getSelectedItem()=="Metre Per Second"&&jComboBox2.getSelectedItem()=="Kilometre Per Hour")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=3.6*a1;
jTextField2.setText(Double.toString(c1)); 
}
 else  if(jComboBox1.getSelectedItem()=="Metre Per Second"&&jComboBox2.getSelectedItem()=="Knot")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=1.94384*a1;
jTextField2.setText(Double.toString(c1)); 
}
 else if(jComboBox1.getSelectedItem()=="Kilometre Per Hour"&&jComboBox2.getSelectedItem()=="Miles Per Hour")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=0.621371*a1;
jTextField2.setText(Double.toString(c1)); 
}
 else  if(jComboBox1.getSelectedItem()=="Kilometre Per Hour"&&jComboBox2.getSelectedItem()=="Foot Per Second")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=0.911344*a1;
jTextField2.setText(Double.toString(c1)); 
}
 else  if(jComboBox1.getSelectedItem()=="Kilometre Per Hour"&&jComboBox2.getSelectedItem()=="Metre Per Second")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=0.277778*a1;
jTextField2.setText(Double.toString(c1)); 
}
 else  if(jComboBox1.getSelectedItem()=="Kilometre Per Hour"&&jComboBox2.getSelectedItem()=="Kilometre Per Hour")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=a1;
jTextField2.setText(Double.toString(c1)); 
}
 else  if(jComboBox1.getSelectedItem()=="Kilometre Per Hour"&&jComboBox2.getSelectedItem()=="Knot")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=0.539957*a1;
jTextField2.setText(Double.toString(c1)); 
}
 else if(jComboBox1.getSelectedItem()=="Knot"&&jComboBox2.getSelectedItem()=="Miles Per Hour")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=1.15078*a1;
jTextField2.setText(Double.toString(c1)); 
}
 else  if(jComboBox1.getSelectedItem()=="Knot"&&jComboBox2.getSelectedItem()=="Foot Per Second")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=1.68781*a1;
jTextField2.setText(Double.toString(c1)); 
}
 else  if(jComboBox1.getSelectedItem()=="Knot"&&jComboBox2.getSelectedItem()=="Metre Per Second")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=0.514444*a1;
jTextField2.setText(Double.toString(c1)); 
}
 else  if(jComboBox1.getSelectedItem()=="Knot"&&jComboBox2.getSelectedItem()=="Kilometre Per Hour")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=1.852*a1;
jTextField2.setText(Double.toString(c1)); 
}
 else  if(jComboBox1.getSelectedItem()=="Knot"&&jComboBox2.getSelectedItem()=="Knot")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=a1;
jTextField2.setText(Double.toString(c1)); 
}

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
System.exit(0);         // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Speed.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Speed.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Speed.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Speed.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Speed().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
