/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package converter;

import java.awt.Color;
import static java.awt.Frame.MAXIMIZED_BOTH;

/**
 *
 * @author RAHUL
 */
public class Time extends javax.swing.JFrame {

    /**
     * Creates new form Time
     */
    public Time() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox<>();
        jButton3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nanosecond", "Microsecond", "Millisecond", "Second", "Minute", "Hour", "Day", "Week", "Month", "Year", "Decade", "Century" }));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nanosecond", "Microsecond", "Millisecond", "Second", "Minute", "Hour", "Day", "Week", "Month", "Year", "Decade", "Century" }));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setText("MENU");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setText("EXIT");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("TIME   CONVERTER");
        jLabel1.setToolTipText("");

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nanosecond", "Microsecond", "Millisecond", "Second", "Minute", "Hour", "Day", "Week", "Month", "Year", "Decade", "Century" }));

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setText("TO");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("-A NOSCIP TECH PRODUCT");

        jLabel3.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("By Hritik jain");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(259, 259, 259)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(204, 204, 204)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(148, 148, 148)
                                .addComponent(jButton3)))
                        .addGap(148, 148, 148)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(254, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(94, 94, 94)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(182, 182, 182)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 173, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(137, 137, 137)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
 FrstFrame f= new FrstFrame();
 f.getContentPane().setBackground(Color.DARK_GRAY);
 f.setExtendedState(MAXIMIZED_BOTH);
f.setVisible(true);
this.dispose();      // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
/*Nanosecond
Microsecond
Millisecond
Second
Minute
Hour
Day
Week
Month
Year
Decade
Century*/
if(jComboBox1.getSelectedItem()=="Nanosecond"&&jComboBox2.getSelectedItem()=="Nanosecond")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=a1;
jTextField2.setText(Double.toString(c1)); 
}
else  if(jComboBox1.getSelectedItem()=="Nanosecond"&&jComboBox2.getSelectedItem()=="Microsecond")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=0.001*a1;
jTextField2.setText(Double.toString(c1)); 
}
else  if(jComboBox1.getSelectedItem()=="Nanosecond"&&jComboBox2.getSelectedItem()=="Millisecond")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=1e-6*a1;
jTextField2.setText(Double.toString(c1)); 
}
else  if(jComboBox1.getSelectedItem()=="Nanosecond"&&jComboBox2.getSelectedItem()=="Second")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=1e-9*a1;
jTextField2.setText(Double.toString(c1)); 
}
else  if(jComboBox1.getSelectedItem()=="Nanosecond"&&jComboBox2.getSelectedItem()=="Minute")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=1.6667e-11*a1;
jTextField2.setText(Double.toString(c1)); 
}
else  if(jComboBox1.getSelectedItem()=="Nanosecond"&&jComboBox2.getSelectedItem()=="Hour")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=2.7778e-13*a1;
jTextField2.setText(Double.toString(c1)); 
}
else  if(jComboBox1.getSelectedItem()=="Nanosecond"&&jComboBox2.getSelectedItem()=="Day")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=1.1574e-14*a1;
jTextField2.setText(Double.toString(c1)); 
}
else  if(jComboBox1.getSelectedItem()=="Nanosecond"&&jComboBox2.getSelectedItem()=="Week")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=1.6534e-15*a1;
jTextField2.setText(Double.toString(c1)); 
}
else  if(jComboBox1.getSelectedItem()=="Nanosecond"&&jComboBox2.getSelectedItem()=="Month")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=3.8052e-16*a1;
jTextField2.setText(Double.toString(c1)); 
}
else  if(jComboBox1.getSelectedItem()=="Nanosecond"&&jComboBox2.getSelectedItem()=="Year")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=3.171e-17*a1;
jTextField2.setText(Double.toString(c1)); 
}
else  if(jComboBox1.getSelectedItem()=="Nanosecond"&&jComboBox2.getSelectedItem()=="Decade")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=3.171e-18*a1;
jTextField2.setText(Double.toString(c1)); 
}
else  if(jComboBox1.getSelectedItem()=="Nanosecond"&&jComboBox2.getSelectedItem()=="Century")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=3.171e-19*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Microsecond"&&jComboBox2.getSelectedItem()=="Nanosecond")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=1000*a1;
jTextField2.setText(Double.toString(c1)); 
}
else  if(jComboBox1.getSelectedItem()=="Microsecond"&&jComboBox2.getSelectedItem()=="Microsecond")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=a1;
jTextField2.setText(Double.toString(c1)); 
}
else  if(jComboBox1.getSelectedItem()=="Microsecond"&&jComboBox2.getSelectedItem()=="Millisecond")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=0.001*a1;
jTextField2.setText(Double.toString(c1)); 
}
else  if(jComboBox1.getSelectedItem()=="Microsecond"&&jComboBox2.getSelectedItem()=="Second")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=1e-6*a1;
jTextField2.setText(Double.toString(c1)); 
}
else  if(jComboBox1.getSelectedItem()=="Microsecond"&&jComboBox2.getSelectedItem()=="Minute")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=1.6667e-8*a1;
jTextField2.setText(Double.toString(c1)); 
}
else  if(jComboBox1.getSelectedItem()=="Microsecond"&&jComboBox2.getSelectedItem()=="Hour")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=2.7778e-10*a1;
jTextField2.setText(Double.toString(c1)); 
}
else  if(jComboBox1.getSelectedItem()=="Microsecond"&&jComboBox2.getSelectedItem()=="Day")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=1.1574e-11*a1;
jTextField2.setText(Double.toString(c1)); 
}
else  if(jComboBox1.getSelectedItem()=="Microsecond"&&jComboBox2.getSelectedItem()=="Week")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=1.6534e-12*a1;
jTextField2.setText(Double.toString(c1)); 
}
else  if(jComboBox1.getSelectedItem()=="Microsecond"&&jComboBox2.getSelectedItem()=="Month")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=3.8052e-13*a1;
jTextField2.setText(Double.toString(c1)); 
}
else  if(jComboBox1.getSelectedItem()=="Microsecond"&&jComboBox2.getSelectedItem()=="Year")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=3.171e-14*a1;
jTextField2.setText(Double.toString(c1)); 
}
else  if(jComboBox1.getSelectedItem()=="Microsecond"&&jComboBox2.getSelectedItem()=="Decade")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=3.171e-15*a1;
jTextField2.setText(Double.toString(c1)); 
}
else  if(jComboBox1.getSelectedItem()=="Microsecond"&&jComboBox2.getSelectedItem()=="Century")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=3.171e-16*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Millisecond"&&jComboBox2.getSelectedItem()=="Nanosecond")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=1e+6*a1;
jTextField2.setText(Double.toString(c1)); 
}
else  if(jComboBox1.getSelectedItem()=="Millisecond"&&jComboBox2.getSelectedItem()=="Microsecond")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=1000*a1;
jTextField2.setText(Double.toString(c1)); 
}
else  if(jComboBox1.getSelectedItem()=="Millisecond"&&jComboBox2.getSelectedItem()=="Millisecond")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=a1;
jTextField2.setText(Double.toString(c1)); 
}
else  if(jComboBox1.getSelectedItem()=="Millisecond"&&jComboBox2.getSelectedItem()=="Second")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=.001*a1;
jTextField2.setText(Double.toString(c1)); 
}
else  if(jComboBox1.getSelectedItem()=="Millisecond"&&jComboBox2.getSelectedItem()=="Minute")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=1.6667e-5*a1;
jTextField2.setText(Double.toString(c1)); 
}
else  if(jComboBox1.getSelectedItem()=="Millisecond"&&jComboBox2.getSelectedItem()=="Hour")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=2.7778e-7*a1;
jTextField2.setText(Double.toString(c1)); 
}
else  if(jComboBox1.getSelectedItem()=="Millisecond"&&jComboBox2.getSelectedItem()=="Day")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=1.1574e-8*a1;
jTextField2.setText(Double.toString(c1)); 
}
else  if(jComboBox1.getSelectedItem()=="Millisecond"&&jComboBox2.getSelectedItem()=="Week")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=1.6534e-9*a1;
jTextField2.setText(Double.toString(c1)); 
}
else  if(jComboBox1.getSelectedItem()=="Millisecond"&&jComboBox2.getSelectedItem()=="Month")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=3.8052e-10*a1;
jTextField2.setText(Double.toString(c1)); 
}
else  if(jComboBox1.getSelectedItem()=="Millisecond"&&jComboBox2.getSelectedItem()=="Year")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=3.171e-11*a1;
jTextField2.setText(Double.toString(c1)); 
}
else  if(jComboBox1.getSelectedItem()=="Millisecond"&&jComboBox2.getSelectedItem()=="Decade")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=3.171e-12*a1;
jTextField2.setText(Double.toString(c1)); 
}
else  if(jComboBox1.getSelectedItem()=="Millisecond"&&jComboBox2.getSelectedItem()=="Century")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=3.171e-13*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Second"&&jComboBox2.getSelectedItem()=="Nanosecond")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=1e+9*a1;
jTextField2.setText(Double.toString(c1)); 
}
else  if(jComboBox1.getSelectedItem()=="Second"&&jComboBox2.getSelectedItem()=="Microsecond")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=1e+6*a1;
jTextField2.setText(Double.toString(c1)); 
}
else  if(jComboBox1.getSelectedItem()=="Second"&&jComboBox2.getSelectedItem()=="Millisecond")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=1000*a1;
jTextField2.setText(Double.toString(c1)); 
}
else  if(jComboBox1.getSelectedItem()=="Second"&&jComboBox2.getSelectedItem()=="Second")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=a1;
jTextField2.setText(Double.toString(c1)); 
}
else  if(jComboBox1.getSelectedItem()=="Second"&&jComboBox2.getSelectedItem()=="Minute")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=0.0166667*a1;
jTextField2.setText(Double.toString(c1)); 
}
else  if(jComboBox1.getSelectedItem()=="Second"&&jComboBox2.getSelectedItem()=="Hour")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=0.000277778*a1;
jTextField2.setText(Double.toString(c1)); 
}
else  if(jComboBox1.getSelectedItem()=="Second"&&jComboBox2.getSelectedItem()=="Day")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=1.1574e-5*a1;
jTextField2.setText(Double.toString(c1)); 
}
else  if(jComboBox1.getSelectedItem()=="Second"&&jComboBox2.getSelectedItem()=="Week")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=1.6534e-6*a1;
jTextField2.setText(Double.toString(c1)); 
}
else  if(jComboBox1.getSelectedItem()=="Second"&&jComboBox2.getSelectedItem()=="Month")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=3.8052e-7*a1;
jTextField2.setText(Double.toString(c1)); 
}
else  if(jComboBox1.getSelectedItem()=="Second"&&jComboBox2.getSelectedItem()=="Year")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=3.171e-8*a1;
jTextField2.setText(Double.toString(c1)); 
}
else  if(jComboBox1.getSelectedItem()=="Second"&&jComboBox2.getSelectedItem()=="Decade")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=3.171e-9*a1;
jTextField2.setText(Double.toString(c1)); 
}
else  if(jComboBox1.getSelectedItem()=="Second"&&jComboBox2.getSelectedItem()=="Century")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=3.171e-10*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Minute"&&jComboBox2.getSelectedItem()=="Nanosecond")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=6e+10*a1;
jTextField2.setText(Double.toString(c1)); 
}
else  if(jComboBox1.getSelectedItem()=="Minute"&&jComboBox2.getSelectedItem()=="Microsecond")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=6e+7*a1;
jTextField2.setText(Double.toString(c1)); 
}
else  if(jComboBox1.getSelectedItem()=="Minute"&&jComboBox2.getSelectedItem()=="Millisecond")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=6e+4*a1;
jTextField2.setText(Double.toString(c1)); 
}
else  if(jComboBox1.getSelectedItem()=="Minute"&&jComboBox2.getSelectedItem()=="Second")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=60*a1;
jTextField2.setText(Double.toString(c1)); 
}
else  if(jComboBox1.getSelectedItem()=="Minute"&&jComboBox2.getSelectedItem()=="Minute")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=a1;
jTextField2.setText(Double.toString(c1)); 
}
else  if(jComboBox1.getSelectedItem()=="Minute"&&jComboBox2.getSelectedItem()=="Hour")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=0.0166667*a1;
jTextField2.setText(Double.toString(c1)); 
}
else  if(jComboBox1.getSelectedItem()=="Minute"&&jComboBox2.getSelectedItem()=="Day")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=0.000694444*a1;
jTextField2.setText(Double.toString(c1)); 
}
else  if(jComboBox1.getSelectedItem()=="Minute"&&jComboBox2.getSelectedItem()=="Week")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=9.9206e-5*a1;
jTextField2.setText(Double.toString(c1)); 
}
else  if(jComboBox1.getSelectedItem()=="Minute"&&jComboBox2.getSelectedItem()=="Month")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=2.2831e-5*a1;
jTextField2.setText(Double.toString(c1)); 
}
else  if(jComboBox1.getSelectedItem()=="Minute"&&jComboBox2.getSelectedItem()=="Year")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=1.9026e-6*a1;
jTextField2.setText(Double.toString(c1)); 
}
else  if(jComboBox1.getSelectedItem()=="Minute"&&jComboBox2.getSelectedItem()=="Decade")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=1.9026e-7*a1;
jTextField2.setText(Double.toString(c1)); 
}
else  if(jComboBox1.getSelectedItem()=="Minute"&&jComboBox2.getSelectedItem()=="Century")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=1.9026e-8*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Hour"&&jComboBox2.getSelectedItem()=="Nanosecond")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=3.6e+12*a1;
jTextField2.setText(Double.toString(c1)); 
}
else  if(jComboBox1.getSelectedItem()=="Hour"&&jComboBox2.getSelectedItem()=="Microsecond")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=3.6e+9*a1;
jTextField2.setText(Double.toString(c1)); 
}
else  if(jComboBox1.getSelectedItem()=="Hour"&&jComboBox2.getSelectedItem()=="Millisecond")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=3.6e+6*a1;
jTextField2.setText(Double.toString(c1)); 
}
else  if(jComboBox1.getSelectedItem()=="Hour"&&jComboBox2.getSelectedItem()=="Second")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=3600*a1;
jTextField2.setText(Double.toString(c1)); 
}
else  if(jComboBox1.getSelectedItem()=="Hour"&&jComboBox2.getSelectedItem()=="Minute")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=60*a1;
jTextField2.setText(Double.toString(c1)); 
}
else  if(jComboBox1.getSelectedItem()=="Hour"&&jComboBox2.getSelectedItem()=="Hour")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=a1;
jTextField2.setText(Double.toString(c1)); 
}
else  if(jComboBox1.getSelectedItem()=="Hour"&&jComboBox2.getSelectedItem()=="Day")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=0.0416667*a1;
jTextField2.setText(Double.toString(c1)); 
}
else  if(jComboBox1.getSelectedItem()=="Hour"&&jComboBox2.getSelectedItem()=="Week")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=0.00595238*a1;
jTextField2.setText(Double.toString(c1)); 
}
else  if(jComboBox1.getSelectedItem()=="Hour"&&jComboBox2.getSelectedItem()=="Month")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=0.00136986*a1;
jTextField2.setText(Double.toString(c1)); 
}
else  if(jComboBox1.getSelectedItem()=="Hour"&&jComboBox2.getSelectedItem()=="Year")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=0.000114155*a1;
jTextField2.setText(Double.toString(c1)); 
}
else  if(jComboBox1.getSelectedItem()=="Hour"&&jComboBox2.getSelectedItem()=="Decade")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=1.1416e-5*a1;
jTextField2.setText(Double.toString(c1)); 
}
else  if(jComboBox1.getSelectedItem()=="Hour"&&jComboBox2.getSelectedItem()=="Century")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=1.1416e-6*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Day"&&jComboBox2.getSelectedItem()=="Nanosecond")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=8.64e+13*a1;
jTextField2.setText(Double.toString(c1)); 
}
else  if(jComboBox1.getSelectedItem()=="Day"&&jComboBox2.getSelectedItem()=="Microsecond")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=8.64e+10*a1;
jTextField2.setText(Double.toString(c1)); 
}
else  if(jComboBox1.getSelectedItem()=="Day"&&jComboBox2.getSelectedItem()=="Millisecond")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=8.64e+7*a1;
jTextField2.setText(Double.toString(c1)); 
}
else  if(jComboBox1.getSelectedItem()=="Day"&&jComboBox2.getSelectedItem()=="Second")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=8.64e+4*a1;
jTextField2.setText(Double.toString(c1)); 
}
else  if(jComboBox1.getSelectedItem()=="Day"&&jComboBox2.getSelectedItem()=="Minute")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=1440*a1;
jTextField2.setText(Double.toString(c1)); 
}
else  if(jComboBox1.getSelectedItem()=="Day"&&jComboBox2.getSelectedItem()=="Hour")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=24*a1;
jTextField2.setText(Double.toString(c1)); 
}
else  if(jComboBox1.getSelectedItem()=="Day"&&jComboBox2.getSelectedItem()=="Day")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=a1;
jTextField2.setText(Double.toString(c1)); 
}
else  if(jComboBox1.getSelectedItem()=="Day"&&jComboBox2.getSelectedItem()=="Week")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=0.142857*a1;
jTextField2.setText(Double.toString(c1)); 
}
else  if(jComboBox1.getSelectedItem()=="Day"&&jComboBox2.getSelectedItem()=="Month")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=0.0328767*a1;
jTextField2.setText(Double.toString(c1)); 
}
else  if(jComboBox1.getSelectedItem()=="Day"&&jComboBox2.getSelectedItem()=="Year")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=0.00273973*a1;
jTextField2.setText(Double.toString(c1)); 
}
else  if(jComboBox1.getSelectedItem()=="Day"&&jComboBox2.getSelectedItem()=="Decade")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=0.000273973*a1;
jTextField2.setText(Double.toString(c1)); 
}
else  if(jComboBox1.getSelectedItem()=="Day"&&jComboBox2.getSelectedItem()=="Century")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=0.0000273973*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Week"&&jComboBox2.getSelectedItem()=="Nanosecond")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=6.048e+14*a1;
jTextField2.setText(Double.toString(c1)); 
}
else  if(jComboBox1.getSelectedItem()=="Week"&&jComboBox2.getSelectedItem()=="Microsecond")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=6.048e+11*a1;
jTextField2.setText(Double.toString(c1)); 
}
else  if(jComboBox1.getSelectedItem()=="Week"&&jComboBox2.getSelectedItem()=="Millisecond")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=6.048e+8*a1;
jTextField2.setText(Double.toString(c1)); 
}
else  if(jComboBox1.getSelectedItem()=="Week"&&jComboBox2.getSelectedItem()=="Second")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=6.048e+5*a1;
jTextField2.setText(Double.toString(c1)); 
}
else  if(jComboBox1.getSelectedItem()=="Week"&&jComboBox2.getSelectedItem()=="Minute")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=10080*a1;
jTextField2.setText(Double.toString(c1)); 
}
else  if(jComboBox1.getSelectedItem()=="Week"&&jComboBox2.getSelectedItem()=="Hour")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=168*a1;
jTextField2.setText(Double.toString(c1)); 
}
else  if(jComboBox1.getSelectedItem()=="Week"&&jComboBox2.getSelectedItem()=="Day")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=24*a1;
jTextField2.setText(Double.toString(c1)); 
}
else  if(jComboBox1.getSelectedItem()=="Week"&&jComboBox2.getSelectedItem()=="Week")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=a1;
jTextField2.setText(Double.toString(c1)); 
}
else  if(jComboBox1.getSelectedItem()=="Week"&&jComboBox2.getSelectedItem()=="Month")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=0.230137*a1;
jTextField2.setText(Double.toString(c1)); 
}
else  if(jComboBox1.getSelectedItem()=="Week"&&jComboBox2.getSelectedItem()=="Year")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=0.0191781*a1;
jTextField2.setText(Double.toString(c1)); 
}
else  if(jComboBox1.getSelectedItem()=="Week"&&jComboBox2.getSelectedItem()=="Decade")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=0.00191781*a1;
jTextField2.setText(Double.toString(c1)); 
}
else  if(jComboBox1.getSelectedItem()=="Week"&&jComboBox2.getSelectedItem()=="Century")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=0.000191781*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Month"&&jComboBox2.getSelectedItem()=="Nanosecond")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=2.628e+15*a1;
jTextField2.setText(Double.toString(c1)); 
}
else  if(jComboBox1.getSelectedItem()=="Month"&&jComboBox2.getSelectedItem()=="Microsecond")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=2.628e+12*a1;
jTextField2.setText(Double.toString(c1)); 
}
else  if(jComboBox1.getSelectedItem()=="Month"&&jComboBox2.getSelectedItem()=="Millisecond")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=2.628e+9*a1;
jTextField2.setText(Double.toString(c1)); 
}
else  if(jComboBox1.getSelectedItem()=="Month"&&jComboBox2.getSelectedItem()=="Second")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=2.628e+6*a1;
jTextField2.setText(Double.toString(c1)); 
}
else  if(jComboBox1.getSelectedItem()=="Month"&&jComboBox2.getSelectedItem()=="Minute")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=43800*a1;
jTextField2.setText(Double.toString(c1)); 
}
else  if(jComboBox1.getSelectedItem()=="Month"&&jComboBox2.getSelectedItem()=="Hour")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=730.001*a1;
jTextField2.setText(Double.toString(c1)); 
}
else  if(jComboBox1.getSelectedItem()=="Month"&&jComboBox2.getSelectedItem()=="Day")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=30.4167*a1;
jTextField2.setText(Double.toString(c1)); 
}
else  if(jComboBox1.getSelectedItem()=="Month"&&jComboBox2.getSelectedItem()=="Week")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=4.34524*a1;
jTextField2.setText(Double.toString(c1)); 
}
else  if(jComboBox1.getSelectedItem()=="Month"&&jComboBox2.getSelectedItem()=="Month")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=a1;
jTextField2.setText(Double.toString(c1)); 
}
else  if(jComboBox1.getSelectedItem()=="Month"&&jComboBox2.getSelectedItem()=="Year")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=0.0833334*a1;
jTextField2.setText(Double.toString(c1)); 
}
else  if(jComboBox1.getSelectedItem()=="Month"&&jComboBox2.getSelectedItem()=="Decade")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=0.00833334*a1;
jTextField2.setText(Double.toString(c1)); 
}
else  if(jComboBox1.getSelectedItem()=="Month"&&jComboBox2.getSelectedItem()=="Century")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=0.000833334*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Year"&&jComboBox2.getSelectedItem()=="Nanosecond")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=3.154e+16*a1;
jTextField2.setText(Double.toString(c1)); 
}
else  if(jComboBox1.getSelectedItem()=="Year"&&jComboBox2.getSelectedItem()=="Microsecond")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=3.154e+13*a1;
jTextField2.setText(Double.toString(c1)); 
}
else  if(jComboBox1.getSelectedItem()=="Year"&&jComboBox2.getSelectedItem()=="Millisecond")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=3.154e+10*a1;
jTextField2.setText(Double.toString(c1)); 
}
else  if(jComboBox1.getSelectedItem()=="Year"&&jComboBox2.getSelectedItem()=="Second")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=3.154e+7*a1;
jTextField2.setText(Double.toString(c1)); 
}
else  if(jComboBox1.getSelectedItem()=="Year"&&jComboBox2.getSelectedItem()=="Minute")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=525600*a1;
jTextField2.setText(Double.toString(c1)); 
}
else  if(jComboBox1.getSelectedItem()=="Year"&&jComboBox2.getSelectedItem()=="Hour")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=8760*a1;
jTextField2.setText(Double.toString(c1)); 
}
else  if(jComboBox1.getSelectedItem()=="Year"&&jComboBox2.getSelectedItem()=="Day")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=365*a1;
jTextField2.setText(Double.toString(c1)); 
}
else  if(jComboBox1.getSelectedItem()=="Year"&&jComboBox2.getSelectedItem()=="Week")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=52.1429*a1;
jTextField2.setText(Double.toString(c1)); 
}
else  if(jComboBox1.getSelectedItem()=="Year"&&jComboBox2.getSelectedItem()=="Month")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=12*a1;
jTextField2.setText(Double.toString(c1)); 
}
else  if(jComboBox1.getSelectedItem()=="Year"&&jComboBox2.getSelectedItem()=="Year")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=a1;
jTextField2.setText(Double.toString(c1)); 
}
else  if(jComboBox1.getSelectedItem()=="Year"&&jComboBox2.getSelectedItem()=="Decade")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=.1*a1;
jTextField2.setText(Double.toString(c1)); 
}
else  if(jComboBox1.getSelectedItem()=="Year"&&jComboBox2.getSelectedItem()=="Century")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=.01*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Decade"&&jComboBox2.getSelectedItem()=="Nanosecond")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=3.154e+17*a1;
jTextField2.setText(Double.toString(c1)); 
}
else  if(jComboBox1.getSelectedItem()=="Decade"&&jComboBox2.getSelectedItem()=="Microsecond")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=3.154e+14*a1;
jTextField2.setText(Double.toString(c1)); 
}
else  if(jComboBox1.getSelectedItem()=="Decade"&&jComboBox2.getSelectedItem()=="Millisecond")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=3.154e+11*a1;
jTextField2.setText(Double.toString(c1)); 
}
else  if(jComboBox1.getSelectedItem()=="Decade"&&jComboBox2.getSelectedItem()=="Second")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=3.154e+8*a1;
jTextField2.setText(Double.toString(c1)); 
}
else  if(jComboBox1.getSelectedItem()=="Decade"&&jComboBox2.getSelectedItem()=="Minute")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=5.256e+6*a1;
jTextField2.setText(Double.toString(c1)); 
}
else  if(jComboBox1.getSelectedItem()=="Decade"&&jComboBox2.getSelectedItem()=="Hour")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=87600*a1;
jTextField2.setText(Double.toString(c1)); 
}
else  if(jComboBox1.getSelectedItem()=="Decade"&&jComboBox2.getSelectedItem()=="Day")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=3650*a1;
jTextField2.setText(Double.toString(c1)); 
}
else  if(jComboBox1.getSelectedItem()=="Decade"&&jComboBox2.getSelectedItem()=="Week")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=521.429*a1;
jTextField2.setText(Double.toString(c1)); 
}
else  if(jComboBox1.getSelectedItem()=="Decade"&&jComboBox2.getSelectedItem()=="Month")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=120*a1;
jTextField2.setText(Double.toString(c1)); 
}
else  if(jComboBox1.getSelectedItem()=="Decade"&&jComboBox2.getSelectedItem()=="Year")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=10*a1;
jTextField2.setText(Double.toString(c1)); 
}
else  if(jComboBox1.getSelectedItem()=="Decade"&&jComboBox2.getSelectedItem()=="Decade")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=a1;
jTextField2.setText(Double.toString(c1)); 
}
else  if(jComboBox1.getSelectedItem()=="Decade"&&jComboBox2.getSelectedItem()=="Century")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=.1*a1;
jTextField2.setText(Double.toString(c1)); 
}
else if(jComboBox1.getSelectedItem()=="Century"&&jComboBox2.getSelectedItem()=="Nanosecond")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=3.154e+18*a1;
jTextField2.setText(Double.toString(c1)); 
}
else  if(jComboBox1.getSelectedItem()=="Century"&&jComboBox2.getSelectedItem()=="Microsecond")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=3.154e+15*a1;
jTextField2.setText(Double.toString(c1)); 
}
else  if(jComboBox1.getSelectedItem()=="Century"&&jComboBox2.getSelectedItem()=="Millisecond")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=3.154e+12*a1;
jTextField2.setText(Double.toString(c1)); 
}
else  if(jComboBox1.getSelectedItem()=="Century"&&jComboBox2.getSelectedItem()=="Second")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=3.154e+9*a1;
jTextField2.setText(Double.toString(c1)); 
}
else  if(jComboBox1.getSelectedItem()=="Century"&&jComboBox2.getSelectedItem()=="Minute")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=5.256e+7*a1;
jTextField2.setText(Double.toString(c1)); 
}
else  if(jComboBox1.getSelectedItem()=="Century"&&jComboBox2.getSelectedItem()=="Hour")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=876000*a1;
jTextField2.setText(Double.toString(c1)); 
}
else  if(jComboBox1.getSelectedItem()=="Century"&&jComboBox2.getSelectedItem()=="Day")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=36500*a1;
jTextField2.setText(Double.toString(c1)); 
}
else  if(jComboBox1.getSelectedItem()=="Century"&&jComboBox2.getSelectedItem()=="Week")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=5214.29*a1;
jTextField2.setText(Double.toString(c1)); 
}
else  if(jComboBox1.getSelectedItem()=="Century"&&jComboBox2.getSelectedItem()=="Month")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=1200*a1;
jTextField2.setText(Double.toString(c1)); 
}
else  if(jComboBox1.getSelectedItem()=="Century"&&jComboBox2.getSelectedItem()=="Year")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=100*a1;
jTextField2.setText(Double.toString(c1)); 
}
else  if(jComboBox1.getSelectedItem()=="Century"&&jComboBox2.getSelectedItem()=="Decade")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=10*a1;
jTextField2.setText(Double.toString(c1)); 
}
else  if(jComboBox1.getSelectedItem()=="Century"&&jComboBox2.getSelectedItem()=="Century")
{
    String a=jTextField1.getText();
    double a1=Double.parseDouble(a);
double c1=a1;
jTextField2.setText(Double.toString(c1)); 
}

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
System.exit(0);         // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Time.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Time.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Time.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Time.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Time().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
